insert into EMPLOYEE (name, job_title, salary) values ('Tiffy', 'Human Resources Assistant II', 431392);
insert into EMPLOYEE (name, job_title, salary) values ('Rica', 'Social Worker', 320675);
insert into EMPLOYEE (name, job_title, salary) values ('Jeana', 'Programmer Analyst II', 267966);
insert into EMPLOYEE (name, job_title, salary) values ('Mechelle', 'Tax Accountant', 439513);
insert into EMPLOYEE (name, job_title, salary) values ('Bren', 'Internal Auditor', 473162);
insert into EMPLOYEE (name, job_title, salary) values ('Corella', 'Engineer III', 261249);
insert into EMPLOYEE (name, job_title, salary) values ('Cherilynn', 'Account Representative III', 82606);
insert into EMPLOYEE (name, job_title, salary) values ('Sophey', 'Speech Pathologist', 418843);
insert into EMPLOYEE (name, job_title, salary) values ('Beverlie', 'Assistant Manager', 161702);
insert into EMPLOYEE (name, job_title, salary) values ('Bari', 'Social Worker', 399109);
insert into EMPLOYEE (name, job_title, salary) values ('Anette', 'Engineer III', 248312);
insert into EMPLOYEE (name, job_title, salary) values ('Melly', 'Developer IV', 293066);
insert into EMPLOYEE (name, job_title, salary) values ('Bambi', 'Teacher', 206702);
insert into EMPLOYEE (name, job_title, salary) values ('Vilhelmina', 'Web Developer I', 461284);
insert into EMPLOYEE (name, job_title, salary) values ('Frederica', 'General Manager', 300488);
insert into EMPLOYEE (name, job_title, salary) values ('Prudence', 'Administrative Assistant IV', 61050);
insert into EMPLOYEE (name, job_title, salary) values ('Gertruda', 'General Manager', 363358);
insert into EMPLOYEE (name, job_title, salary) values ('Athene', 'Quality Engineer', 50363);
insert into EMPLOYEE (name, job_title, salary) values ('Ruthi', 'Senior Editor', 202141);
insert into EMPLOYEE (name, job_title, salary) values ('Izabel', 'Chief Design Engineer', 441903);
insert into EMPLOYEE (name, job_title, salary) values ('Carlye', 'Structural Analysis Engineer', 305124);
insert into EMPLOYEE (name, job_title, salary) values ('Alison', 'Compensation Analyst', 388151);
insert into EMPLOYEE (name, job_title, salary) values ('Eula', 'Financial Advisor', 246424);
insert into EMPLOYEE (name, job_title, salary) values ('Coletta', 'Administrative Assistant IV', 83207);
insert into EMPLOYEE (name, job_title, salary) values ('Carlynn', 'VP Accounting', 413446);
insert into EMPLOYEE (name, job_title, salary) values ('Sula', 'Budget/Accounting Analyst II', 14271);
insert into EMPLOYEE (name, job_title, salary) values ('Bryna', 'Staff Scientist', 496900);
insert into EMPLOYEE (name, job_title, salary) values ('Heidie', 'Project Manager', 299995);
insert into EMPLOYEE (name, job_title, salary) values ('Niki', 'Junior Executive', 123939);
insert into EMPLOYEE (name, job_title, salary) values ('Karina', 'Chemical Engineer', 82763);
insert into EMPLOYEE (name, job_title, salary) values ('Gussy', 'Accountant II', 59314);
insert into EMPLOYEE (name, job_title, salary) values ('Rose', 'General Manager', 46088);
insert into EMPLOYEE (name, job_title, salary) values ('Kamilah', 'Nurse', 328382);
insert into EMPLOYEE (name, job_title, salary) values ('Lexi', 'Nurse', 92668);
insert into EMPLOYEE (name, job_title, salary) values ('Idalina', 'Teacher', 371385);
insert into EMPLOYEE (name, job_title, salary) values ('Johna', 'Assistant Manager', 175311);
insert into EMPLOYEE (name, job_title, salary) values ('Wynne', 'Media Manager III', 270626);
insert into EMPLOYEE (name, job_title, salary) values ('Rosy', 'Geological Engineer', 469207);
insert into EMPLOYEE (name, job_title, salary) values ('Mariele', 'Assistant Media Planner', 467360);
insert into EMPLOYEE (name, job_title, salary) values ('Cynthia', 'Software Consultant', 462885);
insert into EMPLOYEE (name, job_title, salary) values ('Jolee', 'VP Product Management', 68239);
insert into EMPLOYEE (name, job_title, salary) values ('Nalani', 'Accounting Assistant IV', 143326);
insert into EMPLOYEE (name, job_title, salary) values ('Gladi', 'Internal Auditor', 309230);
insert into EMPLOYEE (name, job_title, salary) values ('Fernandina', 'Editor', 73330);
insert into EMPLOYEE (name, job_title, salary) values ('Cybil', 'Assistant Manager', 367673);
insert into EMPLOYEE (name, job_title, salary) values ('Darlleen', 'Software Test Engineer I', 357051);
insert into EMPLOYEE (name, job_title, salary) values ('Maurine', 'Health Coach I', 121270);
insert into EMPLOYEE (name, job_title, salary) values ('Ame', 'Accounting Assistant III', 133485);
insert into EMPLOYEE (name, job_title, salary) values ('Valida', 'Chief Design Engineer', 301333);
insert into EMPLOYEE (name, job_title, salary) values ('Jacki', 'Analyst Programmer', 236492);
insert into EMPLOYEE (name, job_title, salary) values ('Jannel', 'Desktop Support Technician', 62069);
insert into EMPLOYEE (name, job_title, salary) values ('Donny', 'Paralegal', 197775);
insert into EMPLOYEE (name, job_title, salary) values ('Annaliese', 'Senior Sales Associate', 393866);
insert into EMPLOYEE (name, job_title, salary) values ('Renata', 'Human Resources Manager', 142899);
insert into EMPLOYEE (name, job_title, salary) values ('Drucill', 'Design Engineer', 11635);
insert into EMPLOYEE (name, job_title, salary) values ('Viki', 'Environmental Tech', 39635);
insert into EMPLOYEE (name, job_title, salary) values ('Dorri', 'Recruiting Manager', 222641);
insert into EMPLOYEE (name, job_title, salary) values ('Fernanda', 'Media Manager IV', 296108);
insert into EMPLOYEE (name, job_title, salary) values ('Roch', 'Junior Executive', 141273);
insert into EMPLOYEE (name, job_title, salary) values ('Brandise', 'Structural Engineer', 195641);
insert into EMPLOYEE (name, job_title, salary) values ('Elwira', 'Social Worker', 247324);
insert into EMPLOYEE (name, job_title, salary) values ('Etty', 'Payment Adjustment Coordinator', 262184);
insert into EMPLOYEE (name, job_title, salary) values ('Aubrey', 'Sales Representative', 205903);
insert into EMPLOYEE (name, job_title, salary) values ('Milicent', 'Compensation Analyst', 75823);
insert into EMPLOYEE (name, job_title, salary) values ('Hana', 'Quality Control Specialist', 108324);
insert into EMPLOYEE (name, job_title, salary) values ('Deeann', 'Human Resources Assistant III', 385103);
insert into EMPLOYEE (name, job_title, salary) values ('Junie', 'Associate Professor', 337870);
insert into EMPLOYEE (name, job_title, salary) values ('Sam', 'Environmental Tech', 352333);
insert into EMPLOYEE (name, job_title, salary) values ('Berti', 'Marketing Manager', 63063);
insert into EMPLOYEE (name, job_title, salary) values ('Merrill', 'Staff Scientist', 192776);
insert into EMPLOYEE (name, job_title, salary) values ('Ambur', 'Biostatistician II', 60748);
insert into EMPLOYEE (name, job_title, salary) values ('Odessa', 'Human Resources Assistant IV', 469256);
insert into EMPLOYEE (name, job_title, salary) values ('Nancee', 'Assistant Media Planner', 227441);
insert into EMPLOYEE (name, job_title, salary) values ('Kitti', 'Administrative Assistant II', 241396);
insert into EMPLOYEE (name, job_title, salary) values ('Brandise', 'Actuary', 357083);
insert into EMPLOYEE (name, job_title, salary) values ('Tessie', 'Quality Engineer', 15359);
insert into EMPLOYEE (name, job_title, salary) values ('Demetra', 'Technical Writer', 234223);
insert into EMPLOYEE (name, job_title, salary) values ('Jordan', 'GIS Technical Architect', 391458);
insert into EMPLOYEE (name, job_title, salary) values ('Robena', 'Payment Adjustment Coordinator', 333075);
insert into EMPLOYEE (name, job_title, salary) values ('Loleta', 'Research Associate', 185709);
insert into EMPLOYEE (name, job_title, salary) values ('Gabbie', 'VP Accounting', 29735);
insert into EMPLOYEE (name, job_title, salary) values ('Margie', 'Web Developer IV', 130732);
insert into EMPLOYEE (name, job_title, salary) values ('Venus', 'Structural Analysis Engineer', 183598);
insert into EMPLOYEE (name, job_title, salary) values ('Chris', 'Desktop Support Technician', 307935);
insert into EMPLOYEE (name, job_title, salary) values ('Lesly', 'Senior Developer', 363966);
insert into EMPLOYEE (name, job_title, salary) values ('Kaia', 'Data Coordiator', 100740);
insert into EMPLOYEE (name, job_title, salary) values ('Martha', 'Account Representative IV', 498450);
insert into EMPLOYEE (name, job_title, salary) values ('Neysa', 'Social Worker', 119974);
insert into EMPLOYEE (name, job_title, salary) values ('Zandra', 'General Manager', 220745);
insert into EMPLOYEE (name, job_title, salary) values ('Zonnya', 'Marketing Assistant', 274995);
insert into EMPLOYEE (name, job_title, salary) values ('Marcella', 'Graphic Designer', 279873);
insert into EMPLOYEE (name, job_title, salary) values ('Kacey', 'Media Manager I', 438546);
insert into EMPLOYEE (name, job_title, salary) values ('Shayla', 'Senior Quality Engineer', 87946);
insert into EMPLOYEE (name, job_title, salary) values ('Sallie', 'Professor', 330706);
insert into EMPLOYEE (name, job_title, salary) values ('Trista', 'Account Representative I', 276632);
insert into EMPLOYEE (name, job_title, salary) values ('Dulcy', 'Administrative Officer', 302331);
insert into EMPLOYEE (name, job_title, salary) values ('Jeanie', 'Research Nurse', 108517);
insert into EMPLOYEE (name, job_title, salary) values ('Miquela', 'Help Desk Operator', 63676);
insert into EMPLOYEE (name, job_title, salary) values ('Torrie', 'Design Engineer', 50103);
insert into EMPLOYEE (name, job_title, salary) values ('Virgina', 'Help Desk Technician', 156564);
insert into EMPLOYEE (name, job_title, salary) values ('Rhona', 'Community Outreach Specialist', 67646);
insert into EMPLOYEE (name, job_title, salary) values ('Blondy', 'Accounting Assistant II', 414906);
insert into EMPLOYEE (name, job_title, salary) values ('Nancey', 'Chemical Engineer', 120649);
insert into EMPLOYEE (name, job_title, salary) values ('Blakeley', 'Teacher', 249433);
insert into EMPLOYEE (name, job_title, salary) values ('Julee', 'Food Chemist', 219127);
insert into EMPLOYEE (name, job_title, salary) values ('Fae', 'Health Coach IV', 458269);
insert into EMPLOYEE (name, job_title, salary) values ('Masha', 'Actuary', 45551);
insert into EMPLOYEE (name, job_title, salary) values ('Zea', 'Electrical Engineer', 69736);
insert into EMPLOYEE (name, job_title, salary) values ('Caroljean', 'Software Test Engineer IV', 451779);
insert into EMPLOYEE (name, job_title, salary) values ('Cyndy', 'Associate Professor', 294514);
insert into EMPLOYEE (name, job_title, salary) values ('Saundra', 'Technical Writer', 417497);
insert into EMPLOYEE (name, job_title, salary) values ('Charo', 'Senior Editor', 125385);
insert into EMPLOYEE (name, job_title, salary) values ('Lari', 'Human Resources Assistant I', 40088);
insert into EMPLOYEE (name, job_title, salary) values ('Aveline', 'Chief Design Engineer', 102093);
insert into EMPLOYEE (name, job_title, salary) values ('Eolande', 'Computer Systems Analyst IV', 126036);
insert into EMPLOYEE (name, job_title, salary) values ('Georgine', 'Help Desk Operator', 92462);
insert into EMPLOYEE (name, job_title, salary) values ('Cortney', 'Junior Executive', 485951);
insert into EMPLOYEE (name, job_title, salary) values ('Agnes', 'Nuclear Power Engineer', 140159);
insert into EMPLOYEE (name, job_title, salary) values ('Halley', 'Associate Professor', 436316);
insert into EMPLOYEE (name, job_title, salary) values ('Coralyn', 'Operator', 423048);
insert into EMPLOYEE (name, job_title, salary) values ('Maryjo', 'Mechanical Systems Engineer', 498914);
insert into EMPLOYEE (name, job_title, salary) values ('Lari', 'Physical Therapy Assistant', 335487);
insert into EMPLOYEE (name, job_title, salary) values ('Norri', 'Desktop Support Technician', 83640);
insert into EMPLOYEE (name, job_title, salary) values ('Mechelle', 'Analog Circuit Design manager', 471159);
insert into EMPLOYEE (name, job_title, salary) values ('Wilow', 'Product Engineer', 244144);
insert into EMPLOYEE (name, job_title, salary) values ('Wynnie', 'Director of Sales', 58664);
insert into EMPLOYEE (name, job_title, salary) values ('Indira', 'VP Accounting', 14029);
insert into EMPLOYEE (name, job_title, salary) values ('Tallou', 'Teacher', 161707);
insert into EMPLOYEE (name, job_title, salary) values ('Kirbie', 'Programmer II', 312281);
insert into EMPLOYEE (name, job_title, salary) values ('Babbette', 'Clinical Specialist', 291356);
insert into EMPLOYEE (name, job_title, salary) values ('Debbie', 'Associate Professor', 253443);
insert into EMPLOYEE (name, job_title, salary) values ('Loreen', 'Environmental Tech', 96704);
insert into EMPLOYEE (name, job_title, salary) values ('Pammy', 'Safety Technician I', 55587);
insert into EMPLOYEE (name, job_title, salary) values ('Angil', 'Media Manager II', 159564);
insert into EMPLOYEE (name, job_title, salary) values ('Andria', 'Senior Cost Accountant', 281348);
insert into EMPLOYEE (name, job_title, salary) values ('Jessalyn', 'Senior Cost Accountant', 448549);
insert into EMPLOYEE (name, job_title, salary) values ('Frieda', 'Software Consultant', 318196);
insert into EMPLOYEE (name, job_title, salary) values ('Meta', 'Nuclear Power Engineer', 294074);
insert into EMPLOYEE (name, job_title, salary) values ('Edie', 'Data Coordiator', 437170);
insert into EMPLOYEE (name, job_title, salary) values ('Mame', 'Assistant Media Planner', 78437);
insert into EMPLOYEE (name, job_title, salary) values ('Stafani', 'Engineer II', 266215);
insert into EMPLOYEE (name, job_title, salary) values ('Maryellen', 'Dental Hygienist', 491631);
insert into EMPLOYEE (name, job_title, salary) values ('Vinny', 'Assistant Professor', 469008);
insert into EMPLOYEE (name, job_title, salary) values ('Corinne', 'Assistant Professor', 53792);
insert into EMPLOYEE (name, job_title, salary) values ('Laetitia', 'Web Designer I', 443522);
insert into EMPLOYEE (name, job_title, salary) values ('Bernadene', 'Design Engineer', 268047);
insert into EMPLOYEE (name, job_title, salary) values ('Devi', 'Analyst Programmer', 136436);
insert into EMPLOYEE (name, job_title, salary) values ('Evanne', 'Information Systems Manager', 264545);
insert into EMPLOYEE (name, job_title, salary) values ('Tana', 'Analog Circuit Design manager', 350657);
insert into EMPLOYEE (name, job_title, salary) values ('Georgiana', 'Nurse Practicioner', 101810);
insert into EMPLOYEE (name, job_title, salary) values ('Margery', 'Librarian', 368370);
insert into EMPLOYEE (name, job_title, salary) values ('Monika', 'Clinical Specialist', 180671);
insert into EMPLOYEE (name, job_title, salary) values ('Tasha', 'Editor', 291543);
insert into EMPLOYEE (name, job_title, salary) values ('Lara', 'Nuclear Power Engineer', 90327);
insert into EMPLOYEE (name, job_title, salary) values ('Malinda', 'Desktop Support Technician', 493481);
insert into EMPLOYEE (name, job_title, salary) values ('Jemie', 'Research Assistant II', 246080);
insert into EMPLOYEE (name, job_title, salary) values ('Marsha', 'Cost Accountant', 405572);
insert into EMPLOYEE (name, job_title, salary) values ('Jojo', 'Desktop Support Technician', 139036);
insert into EMPLOYEE (name, job_title, salary) values ('Abby', 'Associate Professor', 287566);
insert into EMPLOYEE (name, job_title, salary) values ('Rosita', 'Nuclear Power Engineer', 12622);
insert into EMPLOYEE (name, job_title, salary) values ('Melamie', 'Information Systems Manager', 47241);
insert into EMPLOYEE (name, job_title, salary) values ('Maryanna', 'Staff Scientist', 381322);
insert into EMPLOYEE (name, job_title, salary) values ('Melinde', 'Business Systems Development Analyst', 394503);
insert into EMPLOYEE (name, job_title, salary) values ('Mallory', 'Human Resources Assistant III', 51486);
insert into EMPLOYEE (name, job_title, salary) values ('Silvia', 'Human Resources Assistant II', 369934);
insert into EMPLOYEE (name, job_title, salary) values ('Wilhelmina', 'Tax Accountant', 191862);
insert into EMPLOYEE (name, job_title, salary) values ('Tarrah', 'Nurse Practicioner', 321974);
insert into EMPLOYEE (name, job_title, salary) values ('Jayne', 'Senior Cost Accountant', 489566);
insert into EMPLOYEE (name, job_title, salary) values ('Glenna', 'Business Systems Development Analyst', 413346);
insert into EMPLOYEE (name, job_title, salary) values ('Marin', 'Design Engineer', 65242);
insert into EMPLOYEE (name, job_title, salary) values ('Sherline', 'Community Outreach Specialist', 477742);
insert into EMPLOYEE (name, job_title, salary) values ('Mirilla', 'VP Marketing', 252347);
insert into EMPLOYEE (name, job_title, salary) values ('Marybeth', 'Civil Engineer', 159510);
insert into EMPLOYEE (name, job_title, salary) values ('Fernande', 'Geologist I', 361682);
insert into EMPLOYEE (name, job_title, salary) values ('Sibylle', 'Statistician I', 248043);
insert into EMPLOYEE (name, job_title, salary) values ('Karry', 'Clinical Specialist', 396681);
insert into EMPLOYEE (name, job_title, salary) values ('Goldia', 'VP Product Management', 342934);
insert into EMPLOYEE (name, job_title, salary) values ('Anni', 'Product Engineer', 238086);
insert into EMPLOYEE (name, job_title, salary) values ('Gwenora', 'Payment Adjustment Coordinator', 232736);
insert into EMPLOYEE (name, job_title, salary) values ('Alvira', 'Assistant Media Planner', 268896);
insert into EMPLOYEE (name, job_title, salary) values ('Kristy', 'Occupational Therapist', 279416);
insert into EMPLOYEE (name, job_title, salary) values ('Gertruda', 'Assistant Media Planner', 59275);
insert into EMPLOYEE (name, job_title, salary) values ('Blanca', 'Operator', 339904);
insert into EMPLOYEE (name, job_title, salary) values ('Austin', 'Registered Nurse', 277950);
insert into EMPLOYEE (name, job_title, salary) values ('Leonore', 'Design Engineer', 353582);
insert into EMPLOYEE (name, job_title, salary) values ('Maure', 'Media Manager I', 15566);
insert into EMPLOYEE (name, job_title, salary) values ('Saba', 'Account Representative III', 391205);
insert into EMPLOYEE (name, job_title, salary) values ('Andee', 'Media Manager IV', 497246);
insert into EMPLOYEE (name, job_title, salary) values ('Rafa', 'Compensation Analyst', 10748);
insert into EMPLOYEE (name, job_title, salary) values ('Julita', 'Marketing Manager', 118930);
insert into EMPLOYEE (name, job_title, salary) values ('Penni', 'Chemical Engineer', 484612);
insert into EMPLOYEE (name, job_title, salary) values ('Orly', 'Mechanical Systems Engineer', 108908);
insert into EMPLOYEE (name, job_title, salary) values ('Devina', 'Senior Sales Associate', 186624);
insert into EMPLOYEE (name, job_title, salary) values ('Lorinda', 'Project Manager', 370549);
insert into EMPLOYEE (name, job_title, salary) values ('Elva', 'Executive Secretary', 34854);
insert into EMPLOYEE (name, job_title, salary) values ('Gabriella', 'Information Systems Manager', 179994);
insert into EMPLOYEE (name, job_title, salary) values ('Elyse', 'Research Nurse', 76981);
insert into EMPLOYEE (name, job_title, salary) values ('Eulalie', 'VP Accounting', 99679);
insert into EMPLOYEE (name, job_title, salary) values ('Gabi', 'Nurse Practicioner', 338350);
insert into EMPLOYEE (name, job_title, salary) values ('Shannah', 'Staff Scientist', 231557);
insert into EMPLOYEE (name, job_title, salary) values ('Eileen', 'Quality Control Specialist', 148363);
insert into EMPLOYEE (name, job_title, salary) values ('Madlin', 'Professor', 474542);
insert into EMPLOYEE (name, job_title, salary) values ('Francoise', 'Financial Advisor', 40500);
insert into EMPLOYEE (name, job_title, salary) values ('Cherrita', 'Legal Assistant', 494111);
insert into EMPLOYEE (name, job_title, salary) values ('Sher', 'Paralegal', 141415);
insert into EMPLOYEE (name, job_title, salary) values ('Noami', 'VP Quality Control', 310493);
insert into EMPLOYEE (name, job_title, salary) values ('Gilberte', 'Senior Cost Accountant', 296589);
insert into EMPLOYEE (name, job_title, salary) values ('Dannye', 'Accounting Assistant IV', 338904);
insert into EMPLOYEE (name, job_title, salary) values ('Bethany', 'Senior Developer', 455731);
insert into EMPLOYEE (name, job_title, salary) values ('Vale', 'Librarian', 444091);
insert into EMPLOYEE (name, job_title, salary) values ('Melita', 'Nurse', 78806);
insert into EMPLOYEE (name, job_title, salary) values ('Lilyan', 'Staff Scientist', 52005);
insert into EMPLOYEE (name, job_title, salary) values ('Celestine', 'Web Developer I', 188148);
insert into EMPLOYEE (name, job_title, salary) values ('Gloriane', 'Electrical Engineer', 453614);
insert into EMPLOYEE (name, job_title, salary) values ('Sondra', 'Senior Quality Engineer', 105608);
insert into EMPLOYEE (name, job_title, salary) values ('Frederique', 'General Manager', 384970);
insert into EMPLOYEE (name, job_title, salary) values ('Kippie', 'Programmer IV', 326475);
insert into EMPLOYEE (name, job_title, salary) values ('Kameko', 'VP Quality Control', 406013);
insert into EMPLOYEE (name, job_title, salary) values ('Venita', 'Staff Scientist', 12531);
insert into EMPLOYEE (name, job_title, salary) values ('Windy', 'Business Systems Development Analyst', 277384);
insert into EMPLOYEE (name, job_title, salary) values ('Pat', 'Environmental Specialist', 108633);
insert into EMPLOYEE (name, job_title, salary) values ('Corrina', 'Help Desk Technician', 278210);
insert into EMPLOYEE (name, job_title, salary) values ('Krysta', 'Accounting Assistant II', 457016);
insert into EMPLOYEE (name, job_title, salary) values ('Batsheva', 'Technical Writer', 230759);
insert into EMPLOYEE (name, job_title, salary) values ('Talia', 'Statistician I', 378006);
insert into EMPLOYEE (name, job_title, salary) values ('Jacinthe', 'Administrative Officer', 378761);
insert into EMPLOYEE (name, job_title, salary) values ('Karena', 'Product Engineer', 464153);
insert into EMPLOYEE (name, job_title, salary) values ('Elsa', 'Quality Engineer', 221641);
insert into EMPLOYEE (name, job_title, salary) values ('Merlina', 'Assistant Manager', 363641);
insert into EMPLOYEE (name, job_title, salary) values ('Melva', 'Software Consultant', 130355);
insert into EMPLOYEE (name, job_title, salary) values ('Catriona', 'Sales Associate', 99196);
insert into EMPLOYEE (name, job_title, salary) values ('Jorrie', 'Senior Sales Associate', 124926);
insert into EMPLOYEE (name, job_title, salary) values ('Lil', 'Senior Quality Engineer', 297288);
insert into EMPLOYEE (name, job_title, salary) values ('Hortense', 'Speech Pathologist', 463803);
insert into EMPLOYEE (name, job_title, salary) values ('Gabrila', 'Data Coordiator', 374257);
insert into EMPLOYEE (name, job_title, salary) values ('Caralie', 'Statistician II', 277923);
insert into EMPLOYEE (name, job_title, salary) values ('Dael', 'Legal Assistant', 216191);
insert into EMPLOYEE (name, job_title, salary) values ('Odille', 'Senior Cost Accountant', 232865);
insert into EMPLOYEE (name, job_title, salary) values ('Alexi', 'Dental Hygienist', 102767);
insert into EMPLOYEE (name, job_title, salary) values ('Melodee', 'Speech Pathologist', 330875);
insert into EMPLOYEE (name, job_title, salary) values ('Olga', 'GIS Technical Architect', 115088);
insert into EMPLOYEE (name, job_title, salary) values ('Claudina', 'Analog Circuit Design manager', 400984);
insert into EMPLOYEE (name, job_title, salary) values ('Lenora', 'Dental Hygienist', 426435);
insert into EMPLOYEE (name, job_title, salary) values ('Fey', 'Senior Editor', 429567);
insert into EMPLOYEE (name, job_title, salary) values ('Georgeanne', 'Administrative Assistant III', 96907);
insert into EMPLOYEE (name, job_title, salary) values ('Margarete', 'Nurse Practicioner', 52321);
insert into EMPLOYEE (name, job_title, salary) values ('Kissie', 'Computer Systems Analyst III', 486219);
insert into EMPLOYEE (name, job_title, salary) values ('Evania', 'Recruiter', 346059);
insert into EMPLOYEE (name, job_title, salary) values ('Brunhilde', 'Research Assistant IV', 476182);
insert into EMPLOYEE (name, job_title, salary) values ('Loella', 'Geologist II', 221823);
insert into EMPLOYEE (name, job_title, salary) values ('Kyle', 'Environmental Specialist', 344125);
insert into EMPLOYEE (name, job_title, salary) values ('Feliza', 'VP Marketing', 249286);
insert into EMPLOYEE (name, job_title, salary) values ('Inger', 'Senior Financial Analyst', 337814);
insert into EMPLOYEE (name, job_title, salary) values ('Suzie', 'Tax Accountant', 464462);
insert into EMPLOYEE (name, job_title, salary) values ('Noel', 'Civil Engineer', 188958);
insert into EMPLOYEE (name, job_title, salary) values ('Sascha', 'Administrative Officer', 424248);
insert into EMPLOYEE (name, job_title, salary) values ('Min', 'Quality Control Specialist', 467992);
insert into EMPLOYEE (name, job_title, salary) values ('Cheryl', 'Actuary', 457235);
insert into EMPLOYEE (name, job_title, salary) values ('Jeni', 'Librarian', 60789);
insert into EMPLOYEE (name, job_title, salary) values ('Selena', 'Accountant III', 124417);
insert into EMPLOYEE (name, job_title, salary) values ('Kally', 'Civil Engineer', 353970);
insert into EMPLOYEE (name, job_title, salary) values ('Carly', 'Research Assistant III', 391952);
insert into EMPLOYEE (name, job_title, salary) values ('Isadora', 'Librarian', 218328);
insert into EMPLOYEE (name, job_title, salary) values ('Zondra', 'Administrative Assistant III', 210087);
insert into EMPLOYEE (name, job_title, salary) values ('Danna', 'VP Quality Control', 460366);
insert into EMPLOYEE (name, job_title, salary) values ('Flossie', 'Electrical Engineer', 62457);
insert into EMPLOYEE (name, job_title, salary) values ('Cleopatra', 'Statistician IV', 444545);
insert into EMPLOYEE (name, job_title, salary) values ('Rosemonde', 'Sales Representative', 102083);
insert into EMPLOYEE (name, job_title, salary) values ('Yalonda', 'Structural Analysis Engineer', 457695);
insert into EMPLOYEE (name, job_title, salary) values ('Herta', 'Mechanical Systems Engineer', 273721);
insert into EMPLOYEE (name, job_title, salary) values ('Gabi', 'Environmental Specialist', 56849);
insert into EMPLOYEE (name, job_title, salary) values ('Viv', 'Web Developer I', 386540);
insert into EMPLOYEE (name, job_title, salary) values ('Mandie', 'Assistant Media Planner', 300443);
insert into EMPLOYEE (name, job_title, salary) values ('Abbie', 'Operator', 447182);
insert into EMPLOYEE (name, job_title, salary) values ('Trixy', 'Graphic Designer', 380591);
insert into EMPLOYEE (name, job_title, salary) values ('Sephira', 'Human Resources Assistant I', 310623);
insert into EMPLOYEE (name, job_title, salary) values ('Bethanne', 'General Manager', 224306);
insert into EMPLOYEE (name, job_title, salary) values ('Jammie', 'Environmental Specialist', 346695);
insert into EMPLOYEE (name, job_title, salary) values ('Zelda', 'Nurse', 79306);
insert into EMPLOYEE (name, job_title, salary) values ('April', 'Administrative Assistant II', 455480);
insert into EMPLOYEE (name, job_title, salary) values ('Caresa', 'Senior Sales Associate', 118080);
insert into EMPLOYEE (name, job_title, salary) values ('Melinda', 'Nuclear Power Engineer', 337227);
insert into EMPLOYEE (name, job_title, salary) values ('Kristina', 'Compensation Analyst', 126068);
insert into EMPLOYEE (name, job_title, salary) values ('Neala', 'Assistant Media Planner', 67879);
insert into EMPLOYEE (name, job_title, salary) values ('Penny', 'Editor', 491175);
insert into EMPLOYEE (name, job_title, salary) values ('Magdalen', 'VP Sales', 120273);
insert into EMPLOYEE (name, job_title, salary) values ('Krissy', 'Dental Hygienist', 441469);
insert into EMPLOYEE (name, job_title, salary) values ('Jacinda', 'Recruiter', 119134);
insert into EMPLOYEE (name, job_title, salary) values ('Eddi', 'Assistant Media Planner', 218601);
insert into EMPLOYEE (name, job_title, salary) values ('Valaria', 'Occupational Therapist', 126532);
insert into EMPLOYEE (name, job_title, salary) values ('Lesya', 'Social Worker', 212240);
insert into EMPLOYEE (name, job_title, salary) values ('Isobel', 'Nurse', 161418);
insert into EMPLOYEE (name, job_title, salary) values ('Cecilia', 'Environmental Tech', 154775);
insert into EMPLOYEE (name, job_title, salary) values ('Wylma', 'Programmer Analyst II', 110274);
insert into EMPLOYEE (name, job_title, salary) values ('Fanni', 'Office Assistant IV', 452177);
insert into EMPLOYEE (name, job_title, salary) values ('Jeanna', 'Statistician IV', 128706);
insert into EMPLOYEE (name, job_title, salary) values ('Sharron', 'Chief Design Engineer', 216523);
insert into EMPLOYEE (name, job_title, salary) values ('Zorine', 'VP Accounting', 314791);
insert into EMPLOYEE (name, job_title, salary) values ('Anjela', 'Research Assistant II', 237336);
insert into EMPLOYEE (name, job_title, salary) values ('Juieta', 'Community Outreach Specialist', 139682);
insert into EMPLOYEE (name, job_title, salary) values ('Valentia', 'VP Product Management', 372765);
insert into EMPLOYEE (name, job_title, salary) values ('Karol', 'VP Sales', 494287);
insert into EMPLOYEE (name, job_title, salary) values ('Julienne', 'Business Systems Development Analyst', 360581);
insert into EMPLOYEE (name, job_title, salary) values ('Netta', 'Social Worker', 101952);
insert into EMPLOYEE (name, job_title, salary) values ('Edythe', 'Pharmacist', 191540);
insert into EMPLOYEE (name, job_title, salary) values ('Maia', 'Financial Analyst', 363865);
insert into EMPLOYEE (name, job_title, salary) values ('Emeline', 'Analog Circuit Design manager', 91762);
insert into EMPLOYEE (name, job_title, salary) values ('Ailene', 'Staff Accountant IV', 280366);
insert into EMPLOYEE (name, job_title, salary) values ('Olly', 'Quality Engineer', 496785);
insert into EMPLOYEE (name, job_title, salary) values ('Yasmin', 'GIS Technical Architect', 478512);
insert into EMPLOYEE (name, job_title, salary) values ('Lynnelle', 'Occupational Therapist', 231394);
insert into EMPLOYEE (name, job_title, salary) values ('Janot', 'Programmer Analyst II', 149744);
insert into EMPLOYEE (name, job_title, salary) values ('Emmye', 'Chief Design Engineer', 100388);
insert into EMPLOYEE (name, job_title, salary) values ('Lynett', 'Financial Analyst', 161252);
insert into EMPLOYEE (name, job_title, salary) values ('Monica', 'Health Coach III', 377231);
insert into EMPLOYEE (name, job_title, salary) values ('Page', 'Research Associate', 278714);
insert into EMPLOYEE (name, job_title, salary) values ('Sibyl', 'Civil Engineer', 238153);
insert into EMPLOYEE (name, job_title, salary) values ('Virginia', 'Business Systems Development Analyst', 182347);
insert into EMPLOYEE (name, job_title, salary) values ('Glory', 'Financial Analyst', 181771);
insert into EMPLOYEE (name, job_title, salary) values ('Meg', 'Internal Auditor', 78963);
insert into EMPLOYEE (name, job_title, salary) values ('Kathye', 'Librarian', 51920);
insert into EMPLOYEE (name, job_title, salary) values ('Jilly', 'Web Designer I', 329691);
insert into EMPLOYEE (name, job_title, salary) values ('Demeter', 'Chemical Engineer', 329374);
insert into EMPLOYEE (name, job_title, salary) values ('Amaleta', 'Marketing Manager', 429611);
insert into EMPLOYEE (name, job_title, salary) values ('Jade', 'Administrative Officer', 455026);
insert into EMPLOYEE (name, job_title, salary) values ('Kathryne', 'Office Assistant II', 361485);
insert into EMPLOYEE (name, job_title, salary) values ('Antoinette', 'Analog Circuit Design manager', 96505);
insert into EMPLOYEE (name, job_title, salary) values ('Ryann', 'Assistant Manager', 365064);
insert into EMPLOYEE (name, job_title, salary) values ('Nannette', 'Professor', 226817);
insert into EMPLOYEE (name, job_title, salary) values ('Gene', 'Financial Advisor', 380948);
insert into EMPLOYEE (name, job_title, salary) values ('Trudie', 'Dental Hygienist', 431142);
insert into EMPLOYEE (name, job_title, salary) values ('Tonya', 'Analyst Programmer', 261839);
insert into EMPLOYEE (name, job_title, salary) values ('Jerrilee', 'Assistant Professor', 98306);
insert into EMPLOYEE (name, job_title, salary) values ('Clara', 'Junior Executive', 439953);
insert into EMPLOYEE (name, job_title, salary) values ('Clarette', 'Senior Editor', 452856);
insert into EMPLOYEE (name, job_title, salary) values ('Claude', 'Actuary', 125607);
insert into EMPLOYEE (name, job_title, salary) values ('Dede', 'Information Systems Manager', 457249);
insert into EMPLOYEE (name, job_title, salary) values ('Kristien', 'Clinical Specialist', 105474);
insert into EMPLOYEE (name, job_title, salary) values ('Carol-jean', 'Accounting Assistant III', 415898);
insert into EMPLOYEE (name, job_title, salary) values ('Kerrin', 'Senior Cost Accountant', 359863);
insert into EMPLOYEE (name, job_title, salary) values ('Nadean', 'Accounting Assistant II', 422721);
insert into EMPLOYEE (name, job_title, salary) values ('Elnore', 'Programmer III', 300042);
insert into EMPLOYEE (name, job_title, salary) values ('Fern', 'Electrical Engineer', 488510);
insert into EMPLOYEE (name, job_title, salary) values ('Sadie', 'Quality Control Specialist', 286580);
insert into EMPLOYEE (name, job_title, salary) values ('Cammie', 'Administrative Officer', 394613);
insert into EMPLOYEE (name, job_title, salary) values ('Shaine', 'Civil Engineer', 202228);
insert into EMPLOYEE (name, job_title, salary) values ('Dorolice', 'Nurse Practicioner', 298006);
insert into EMPLOYEE (name, job_title, salary) values ('Marianne', 'Technical Writer', 322131);
insert into EMPLOYEE (name, job_title, salary) values ('Wendye', 'Financial Analyst', 338823);
insert into EMPLOYEE (name, job_title, salary) values ('Valery', 'Programmer Analyst IV', 491776);
insert into EMPLOYEE (name, job_title, salary) values ('Phelia', 'Research Nurse', 293417);
insert into EMPLOYEE (name, job_title, salary) values ('Karol', 'Software Consultant', 429576);
insert into EMPLOYEE (name, job_title, salary) values ('Lexy', 'Financial Advisor', 27430);
insert into EMPLOYEE (name, job_title, salary) values ('Karee', 'Web Designer IV', 438049);
insert into EMPLOYEE (name, job_title, salary) values ('Constancy', 'Account Representative I', 441235);
insert into EMPLOYEE (name, job_title, salary) values ('Sheila', 'Health Coach I', 446695);
insert into EMPLOYEE (name, job_title, salary) values ('Bonnee', 'Quality Engineer', 222437);
insert into EMPLOYEE (name, job_title, salary) values ('Robin', 'Physical Therapy Assistant', 314614);
insert into EMPLOYEE (name, job_title, salary) values ('Chad', 'Senior Quality Engineer', 320059);
insert into EMPLOYEE (name, job_title, salary) values ('Sileas', 'Senior Developer', 350333);
insert into EMPLOYEE (name, job_title, salary) values ('Guinna', 'Biostatistician II', 39386);
insert into EMPLOYEE (name, job_title, salary) values ('Tamarra', 'Assistant Manager', 142848);
insert into EMPLOYEE (name, job_title, salary) values ('Janina', 'Junior Executive', 50001);
insert into EMPLOYEE (name, job_title, salary) values ('Kristal', 'VP Accounting', 480813);
insert into EMPLOYEE (name, job_title, salary) values ('Aaren', 'Data Coordiator', 348267);
insert into EMPLOYEE (name, job_title, salary) values ('Pippa', 'Account Executive', 387966);
insert into EMPLOYEE (name, job_title, salary) values ('Carey', 'VP Marketing', 275665);
insert into EMPLOYEE (name, job_title, salary) values ('Karol', 'Biostatistician IV', 463753);
insert into EMPLOYEE (name, job_title, salary) values ('Scarlett', 'Occupational Therapist', 112680);
insert into EMPLOYEE (name, job_title, salary) values ('Celestyn', 'Product Engineer', 426877);
insert into EMPLOYEE (name, job_title, salary) values ('Crystie', 'Programmer Analyst III', 152071);
insert into EMPLOYEE (name, job_title, salary) values ('Candace', 'Executive Secretary', 451935);
insert into EMPLOYEE (name, job_title, salary) values ('Donielle', 'Database Administrator III', 173562);
insert into EMPLOYEE (name, job_title, salary) values ('Stacie', 'Registered Nurse', 140013);
insert into EMPLOYEE (name, job_title, salary) values ('Elonore', 'Nuclear Power Engineer', 229704);
insert into EMPLOYEE (name, job_title, salary) values ('Dody', 'Recruiting Manager', 94416);
insert into EMPLOYEE (name, job_title, salary) values ('Mirabelle', 'Project Manager', 46158);
insert into EMPLOYEE (name, job_title, salary) values ('Wandis', 'Clinical Specialist', 332198);
insert into EMPLOYEE (name, job_title, salary) values ('Maureene', 'Senior Quality Engineer', 467989);
insert into EMPLOYEE (name, job_title, salary) values ('Grissel', 'GIS Technical Architect', 352597);
insert into EMPLOYEE (name, job_title, salary) values ('Tresa', 'Executive Secretary', 60353);
insert into EMPLOYEE (name, job_title, salary) values ('Revkah', 'Pharmacist', 93021);
insert into EMPLOYEE (name, job_title, salary) values ('Melisandra', 'Senior Cost Accountant', 298309);
insert into EMPLOYEE (name, job_title, salary) values ('Jobey', 'Civil Engineer', 429692);
insert into EMPLOYEE (name, job_title, salary) values ('Kaila', 'Internal Auditor', 76267);
insert into EMPLOYEE (name, job_title, salary) values ('Brandi', 'Quality Control Specialist', 431076);
insert into EMPLOYEE (name, job_title, salary) values ('Arlee', 'Tax Accountant', 441774);
insert into EMPLOYEE (name, job_title, salary) values ('Deva', 'Human Resources Assistant IV', 484364);
insert into EMPLOYEE (name, job_title, salary) values ('Roslyn', 'Food Chemist', 413559);
insert into EMPLOYEE (name, job_title, salary) values ('Gwenny', 'Dental Hygienist', 25986);
insert into EMPLOYEE (name, job_title, salary) values ('Katrinka', 'VP Quality Control', 455223);
insert into EMPLOYEE (name, job_title, salary) values ('Rosie', 'Speech Pathologist', 286731);
insert into EMPLOYEE (name, job_title, salary) values ('Sigrid', 'Data Coordiator', 372026);
insert into EMPLOYEE (name, job_title, salary) values ('Rosanne', 'Account Representative II', 498934);
insert into EMPLOYEE (name, job_title, salary) values ('Blondelle', 'Structural Analysis Engineer', 197304);
insert into EMPLOYEE (name, job_title, salary) values ('Etti', 'Assistant Media Planner', 94275);
insert into EMPLOYEE (name, job_title, salary) values ('Reine', 'Structural Engineer', 258889);
insert into EMPLOYEE (name, job_title, salary) values ('Evita', 'Product Engineer', 199302);
insert into EMPLOYEE (name, job_title, salary) values ('Arda', 'Physical Therapy Assistant', 380959);
insert into EMPLOYEE (name, job_title, salary) values ('Cristi', 'Geologist III', 187031);
insert into EMPLOYEE (name, job_title, salary) values ('Kira', 'Editor', 147332);
insert into EMPLOYEE (name, job_title, salary) values ('Leonanie', 'Health Coach III', 298990);
insert into EMPLOYEE (name, job_title, salary) values ('Korie', 'Speech Pathologist', 465874);
insert into EMPLOYEE (name, job_title, salary) values ('Gwendolin', 'Teacher', 112963);
insert into EMPLOYEE (name, job_title, salary) values ('Georgette', 'Health Coach I', 191212);
insert into EMPLOYEE (name, job_title, salary) values ('Henrietta', 'Director of Sales', 166874);
insert into EMPLOYEE (name, job_title, salary) values ('Dodie', 'Internal Auditor', 410131);
insert into EMPLOYEE (name, job_title, salary) values ('Danette', 'Analog Circuit Design manager', 151463);
insert into EMPLOYEE (name, job_title, salary) values ('Ivie', 'Programmer Analyst I', 497205);
insert into EMPLOYEE (name, job_title, salary) values ('Mareah', 'Payment Adjustment Coordinator', 347895);
insert into EMPLOYEE (name, job_title, salary) values ('Leandra', 'Marketing Manager', 12498);
insert into EMPLOYEE (name, job_title, salary) values ('Pet', 'Data Coordiator', 252427);
insert into EMPLOYEE (name, job_title, salary) values ('Glynda', 'Research Nurse', 260696);
insert into EMPLOYEE (name, job_title, salary) values ('Annabelle', 'Database Administrator III', 147833);
insert into EMPLOYEE (name, job_title, salary) values ('Mareah', 'Accountant I', 244914);
insert into EMPLOYEE (name, job_title, salary) values ('Rubia', 'Research Nurse', 212496);
insert into EMPLOYEE (name, job_title, salary) values ('Kanya', 'Structural Analysis Engineer', 359885);
insert into EMPLOYEE (name, job_title, salary) values ('Karol', 'Editor', 473616);
insert into EMPLOYEE (name, job_title, salary) values ('Rochella', 'Programmer Analyst IV', 85499);
insert into EMPLOYEE (name, job_title, salary) values ('Angy', 'Physical Therapy Assistant', 143440);
insert into EMPLOYEE (name, job_title, salary) values ('Kessiah', 'Community Outreach Specialist', 130091);
insert into EMPLOYEE (name, job_title, salary) values ('Erna', 'Data Coordiator', 461956);
insert into EMPLOYEE (name, job_title, salary) values ('Brittni', 'Analyst Programmer', 20234);
insert into EMPLOYEE (name, job_title, salary) values ('Glory', 'Safety Technician II', 148776);
insert into EMPLOYEE (name, job_title, salary) values ('Danna', 'Marketing Manager', 476739);
insert into EMPLOYEE (name, job_title, salary) values ('Codie', 'Data Coordiator', 424965);
insert into EMPLOYEE (name, job_title, salary) values ('Marlo', 'Statistician III', 237441);
insert into EMPLOYEE (name, job_title, salary) values ('Gilligan', 'Engineer III', 79388);
insert into EMPLOYEE (name, job_title, salary) values ('Gillie', 'Speech Pathologist', 392872);
insert into EMPLOYEE (name, job_title, salary) values ('Ailene', 'Design Engineer', 316349);
insert into EMPLOYEE (name, job_title, salary) values ('Agna', 'Engineer IV', 202322);
insert into EMPLOYEE (name, job_title, salary) values ('Elyn', 'Structural Analysis Engineer', 448432);
insert into EMPLOYEE (name, job_title, salary) values ('Simonne', 'Computer Systems Analyst III', 17032);
insert into EMPLOYEE (name, job_title, salary) values ('Amie', 'Desktop Support Technician', 224898);
insert into EMPLOYEE (name, job_title, salary) values ('Jen', 'Nurse Practicioner', 98530);
insert into EMPLOYEE (name, job_title, salary) values ('Neilla', 'Structural Analysis Engineer', 85499);
insert into EMPLOYEE (name, job_title, salary) values ('Teressa', 'Registered Nurse', 322212);
insert into EMPLOYEE (name, job_title, salary) values ('Vittoria', 'Software Consultant', 89762);
insert into EMPLOYEE (name, job_title, salary) values ('Brana', 'Food Chemist', 409934);
insert into EMPLOYEE (name, job_title, salary) values ('Malia', 'Senior Quality Engineer', 446311);
insert into EMPLOYEE (name, job_title, salary) values ('Gus', 'Marketing Assistant', 81915);
insert into EMPLOYEE (name, job_title, salary) values ('Liesa', 'Web Developer I', 71490);
insert into EMPLOYEE (name, job_title, salary) values ('Amelie', 'Pharmacist', 313439);
insert into EMPLOYEE (name, job_title, salary) values ('Michal', 'Pharmacist', 20207);
insert into EMPLOYEE (name, job_title, salary) values ('Aurelie', 'Administrative Officer', 451715);
insert into EMPLOYEE (name, job_title, salary) values ('Sallyann', 'Senior Editor', 150201);
insert into EMPLOYEE (name, job_title, salary) values ('Kelci', 'Legal Assistant', 388698);
insert into EMPLOYEE (name, job_title, salary) values ('Susannah', 'Product Engineer', 232492);
insert into EMPLOYEE (name, job_title, salary) values ('Letisha', 'Editor', 346514);
insert into EMPLOYEE (name, job_title, salary) values ('Lorraine', 'Research Nurse', 495091);
insert into EMPLOYEE (name, job_title, salary) values ('Isabelita', 'VP Accounting', 261255);
insert into EMPLOYEE (name, job_title, salary) values ('Amitie', 'Statistician III', 32052);
insert into EMPLOYEE (name, job_title, salary) values ('Nadeen', 'Electrical Engineer', 472403);
insert into EMPLOYEE (name, job_title, salary) values ('Kellie', 'Account Representative IV', 270432);
insert into EMPLOYEE (name, job_title, salary) values ('Adelaide', 'Professor', 18707);
insert into EMPLOYEE (name, job_title, salary) values ('Danya', 'Food Chemist', 411851);
insert into EMPLOYEE (name, job_title, salary) values ('Frank', 'Analog Circuit Design manager', 184491);
insert into EMPLOYEE (name, job_title, salary) values ('Enrika', 'Senior Financial Analyst', 452091);
insert into EMPLOYEE (name, job_title, salary) values ('Tamqrah', 'Assistant Professor', 265469);
insert into EMPLOYEE (name, job_title, salary) values ('Benetta', 'Teacher', 317598);
insert into EMPLOYEE (name, job_title, salary) values ('Berna', 'Automation Specialist IV', 449058);
insert into EMPLOYEE (name, job_title, salary) values ('Zandra', 'VP Accounting', 129040);
insert into EMPLOYEE (name, job_title, salary) values ('Katharyn', 'VP Accounting', 369259);
insert into EMPLOYEE (name, job_title, salary) values ('Randy', 'Financial Advisor', 249829);
insert into EMPLOYEE (name, job_title, salary) values ('Kinna', 'Administrative Officer', 223256);
insert into EMPLOYEE (name, job_title, salary) values ('Gretel', 'Data Coordiator', 255284);
insert into EMPLOYEE (name, job_title, salary) values ('Tommi', 'Database Administrator II', 22076);
insert into EMPLOYEE (name, job_title, salary) values ('Gerrie', 'Budget/Accounting Analyst III', 464371);
insert into EMPLOYEE (name, job_title, salary) values ('Valerie', 'Business Systems Development Analyst', 51753);
insert into EMPLOYEE (name, job_title, salary) values ('Almeta', 'Product Engineer', 251201);
insert into EMPLOYEE (name, job_title, salary) values ('Carolyn', 'Marketing Assistant', 303753);
insert into EMPLOYEE (name, job_title, salary) values ('Rosamund', 'Quality Engineer', 53711);
insert into EMPLOYEE (name, job_title, salary) values ('Katheryn', 'Senior Developer', 358562);
insert into EMPLOYEE (name, job_title, salary) values ('Renie', 'Data Coordiator', 434407);
insert into EMPLOYEE (name, job_title, salary) values ('Alecia', 'Speech Pathologist', 190189);
insert into EMPLOYEE (name, job_title, salary) values ('Zarah', 'Structural Engineer', 204553);
insert into EMPLOYEE (name, job_title, salary) values ('Cleo', 'Computer Systems Analyst II', 291807);
insert into EMPLOYEE (name, job_title, salary) values ('Martie', 'Product Engineer', 273480);
insert into EMPLOYEE (name, job_title, salary) values ('Chrystal', 'Information Systems Manager', 57431);
insert into EMPLOYEE (name, job_title, salary) values ('Rebekah', 'Human Resources Assistant I', 135438);
insert into EMPLOYEE (name, job_title, salary) values ('Goldi', 'Junior Executive', 383949);
insert into EMPLOYEE (name, job_title, salary) values ('Tamera', 'Human Resources Manager', 54802);
insert into EMPLOYEE (name, job_title, salary) values ('Adrian', 'Nurse Practicioner', 449839);
insert into EMPLOYEE (name, job_title, salary) values ('Maria', 'Business Systems Development Analyst', 404707);
insert into EMPLOYEE (name, job_title, salary) values ('Sheela', 'Structural Analysis Engineer', 486614);
insert into EMPLOYEE (name, job_title, salary) values ('Janene', 'Account Coordinator', 476155);
insert into EMPLOYEE (name, job_title, salary) values ('Pammie', 'Health Coach III', 156774);
insert into EMPLOYEE (name, job_title, salary) values ('Jasmina', 'Electrical Engineer', 373866);
insert into EMPLOYEE (name, job_title, salary) values ('Letti', 'Software Engineer II', 139599);
insert into EMPLOYEE (name, job_title, salary) values ('Bobbee', 'Financial Analyst', 414888);
insert into EMPLOYEE (name, job_title, salary) values ('Timothea', 'Senior Sales Associate', 202172);
insert into EMPLOYEE (name, job_title, salary) values ('Nadya', 'Safety Technician II', 493168);
insert into EMPLOYEE (name, job_title, salary) values ('Paulina', 'Associate Professor', 432282);
insert into EMPLOYEE (name, job_title, salary) values ('Allix', 'Account Representative IV', 320673);
insert into EMPLOYEE (name, job_title, salary) values ('Marquita', 'Sales Representative', 413899);
insert into EMPLOYEE (name, job_title, salary) values ('Eilis', 'Structural Analysis Engineer', 104053);
insert into EMPLOYEE (name, job_title, salary) values ('Holly-anne', 'Account Executive', 363998);
insert into EMPLOYEE (name, job_title, salary) values ('Bibi', 'Account Executive', 291391);
insert into EMPLOYEE (name, job_title, salary) values ('Nanine', 'Senior Financial Analyst', 176221);
insert into EMPLOYEE (name, job_title, salary) values ('Fanny', 'Senior Developer', 98993);
insert into EMPLOYEE (name, job_title, salary) values ('Anthiathia', 'Assistant Media Planner', 59683);
insert into EMPLOYEE (name, job_title, salary) values ('Ula', 'Occupational Therapist', 376708);
insert into EMPLOYEE (name, job_title, salary) values ('Salli', 'Senior Quality Engineer', 458673);
insert into EMPLOYEE (name, job_title, salary) values ('Vicky', 'Social Worker', 207290);
insert into EMPLOYEE (name, job_title, salary) values ('Farra', 'Systems Administrator III', 353245);
insert into EMPLOYEE (name, job_title, salary) values ('Gerladina', 'Recruiter', 243470);
insert into EMPLOYEE (name, job_title, salary) values ('Prudy', 'Recruiting Manager', 62188);
insert into EMPLOYEE (name, job_title, salary) values ('Phoebe', 'Nurse Practicioner', 153573);
insert into EMPLOYEE (name, job_title, salary) values ('Nerte', 'Biostatistician IV', 489354);
insert into EMPLOYEE (name, job_title, salary) values ('Shirl', 'Analyst Programmer', 299539);
insert into EMPLOYEE (name, job_title, salary) values ('Roanne', 'Product Engineer', 207242);
insert into EMPLOYEE (name, job_title, salary) values ('Bill', 'Technical Writer', 67001);
insert into EMPLOYEE (name, job_title, salary) values ('Melody', 'Operator', 216031);
insert into EMPLOYEE (name, job_title, salary) values ('Germana', 'Computer Systems Analyst III', 321306);
insert into EMPLOYEE (name, job_title, salary) values ('Courtenay', 'Research Nurse', 307407);
insert into EMPLOYEE (name, job_title, salary) values ('Lin', 'Research Nurse', 170621);
insert into EMPLOYEE (name, job_title, salary) values ('Kala', 'Marketing Manager', 405272);
insert into EMPLOYEE (name, job_title, salary) values ('Lorena', 'Software Test Engineer I', 409188);
insert into EMPLOYEE (name, job_title, salary) values ('Dede', 'Office Assistant IV', 294264);
insert into EMPLOYEE (name, job_title, salary) values ('Rhonda', 'Sales Representative', 322963);
insert into EMPLOYEE (name, job_title, salary) values ('Elena', 'Engineer II', 269480);
insert into EMPLOYEE (name, job_title, salary) values ('Caroline', 'Structural Engineer', 302919);
insert into EMPLOYEE (name, job_title, salary) values ('Giulietta', 'Environmental Specialist', 270879);
insert into EMPLOYEE (name, job_title, salary) values ('Nat', 'Business Systems Development Analyst', 41176);
insert into EMPLOYEE (name, job_title, salary) values ('Suzanna', 'Account Coordinator', 361219);
insert into EMPLOYEE (name, job_title, salary) values ('Lizzie', 'Assistant Manager', 238789);
insert into EMPLOYEE (name, job_title, salary) values ('Ilsa', 'Software Engineer III', 70500);
insert into EMPLOYEE (name, job_title, salary) values ('Corella', 'Food Chemist', 414023);
insert into EMPLOYEE (name, job_title, salary) values ('Raeann', 'Research Associate', 412929);
insert into EMPLOYEE (name, job_title, salary) values ('Nikki', 'Recruiting Manager', 376485);
insert into EMPLOYEE (name, job_title, salary) values ('Augusta', 'Mechanical Systems Engineer', 178254);
insert into EMPLOYEE (name, job_title, salary) values ('Mercy', 'Professor', 167852);
insert into EMPLOYEE (name, job_title, salary) values ('Glennie', 'Web Designer IV', 288748);
insert into EMPLOYEE (name, job_title, salary) values ('Elita', 'Business Systems Development Analyst', 331287);
insert into EMPLOYEE (name, job_title, salary) values ('Ree', 'Environmental Specialist', 121880);
insert into EMPLOYEE (name, job_title, salary) values ('Verine', 'Budget/Accounting Analyst IV', 437063);
insert into EMPLOYEE (name, job_title, salary) values ('Phaidra', 'Senior Quality Engineer', 446534);
insert into EMPLOYEE (name, job_title, salary) values ('Kali', 'Accountant II', 318604);
insert into EMPLOYEE (name, job_title, salary) values ('Laurene', 'Help Desk Technician', 427519);
insert into EMPLOYEE (name, job_title, salary) values ('Bonnie', 'Senior Editor', 81431);
insert into EMPLOYEE (name, job_title, salary) values ('Devonne', 'Technical Writer', 71084);
insert into EMPLOYEE (name, job_title, salary) values ('Letty', 'Staff Accountant II', 61615);
insert into EMPLOYEE (name, job_title, salary) values ('Prudi', 'VP Quality Control', 188222);
insert into EMPLOYEE (name, job_title, salary) values ('Tamma', 'Office Assistant IV', 74498);
insert into EMPLOYEE (name, job_title, salary) values ('Flss', 'Chemical Engineer', 300154);
insert into EMPLOYEE (name, job_title, salary) values ('Rozanna', 'VP Accounting', 351961);
insert into EMPLOYEE (name, job_title, salary) values ('Doretta', 'Structural Engineer', 462341);
insert into EMPLOYEE (name, job_title, salary) values ('Sheila', 'Mechanical Systems Engineer', 46089);
insert into EMPLOYEE (name, job_title, salary) values ('Allx', 'Desktop Support Technician', 314888);
insert into EMPLOYEE (name, job_title, salary) values ('Maureene', 'VP Quality Control', 38670);
insert into EMPLOYEE (name, job_title, salary) values ('Shelia', 'Financial Advisor', 42192);
insert into EMPLOYEE (name, job_title, salary) values ('Camilla', 'Desktop Support Technician', 151938);
insert into EMPLOYEE (name, job_title, salary) values ('Pansie', 'Accountant IV', 331343);
insert into EMPLOYEE (name, job_title, salary) values ('Meriel', 'Environmental Specialist', 72412);
insert into EMPLOYEE (name, job_title, salary) values ('Arabele', 'General Manager', 314644);
insert into EMPLOYEE (name, job_title, salary) values ('Catie', 'GIS Technical Architect', 210162);
insert into EMPLOYEE (name, job_title, salary) values ('Rory', 'Administrative Officer', 80572);
insert into EMPLOYEE (name, job_title, salary) values ('Marna', 'Nurse Practicioner', 258263);
insert into EMPLOYEE (name, job_title, salary) values ('Marquita', 'Environmental Specialist', 377152);
insert into EMPLOYEE (name, job_title, salary) values ('Kalie', 'Database Administrator I', 293129);
insert into EMPLOYEE (name, job_title, salary) values ('Kathy', 'Internal Auditor', 87806);
insert into EMPLOYEE (name, job_title, salary) values ('Junia', 'Paralegal', 317681);
insert into EMPLOYEE (name, job_title, salary) values ('Marsha', 'Structural Analysis Engineer', 261151);
insert into EMPLOYEE (name, job_title, salary) values ('Estell', 'Desktop Support Technician', 462412);
insert into EMPLOYEE (name, job_title, salary) values ('Kala', 'Help Desk Technician', 343070);
insert into EMPLOYEE (name, job_title, salary) values ('Rochella', 'Administrative Officer', 257427);
insert into EMPLOYEE (name, job_title, salary) values ('Justine', 'Research Assistant III', 349043);
insert into EMPLOYEE (name, job_title, salary) values ('Farand', 'Desktop Support Technician', 83775);
insert into EMPLOYEE (name, job_title, salary) values ('Tamma', 'Mechanical Systems Engineer', 447756);
insert into EMPLOYEE (name, job_title, salary) values ('Leanna', 'Analyst Programmer', 436062);
insert into EMPLOYEE (name, job_title, salary) values ('Madelin', 'Compensation Analyst', 12840);
insert into EMPLOYEE (name, job_title, salary) values ('Edin', 'Developer III', 212052);
insert into EMPLOYEE (name, job_title, salary) values ('Jennica', 'Actuary', 157834);
insert into EMPLOYEE (name, job_title, salary) values ('Karolina', 'Information Systems Manager', 357587);
insert into EMPLOYEE (name, job_title, salary) values ('Briney', 'Electrical Engineer', 162678);
insert into EMPLOYEE (name, job_title, salary) values ('Ailee', 'Computer Systems Analyst III', 88221);
insert into EMPLOYEE (name, job_title, salary) values ('Gustie', 'Automation Specialist II', 243670);
insert into EMPLOYEE (name, job_title, salary) values ('Cindie', 'Assistant Professor', 265423);
insert into EMPLOYEE (name, job_title, salary) values ('Avrit', 'Sales Representative', 308163);
insert into EMPLOYEE (name, job_title, salary) values ('Yolane', 'Cost Accountant', 440728);
insert into EMPLOYEE (name, job_title, salary) values ('Koressa', 'Information Systems Manager', 229007);
insert into EMPLOYEE (name, job_title, salary) values ('Tamiko', 'Actuary', 374887);
insert into EMPLOYEE (name, job_title, salary) values ('Paulette', 'Data Coordiator', 66786);
insert into EMPLOYEE (name, job_title, salary) values ('Devin', 'Account Coordinator', 244357);
insert into EMPLOYEE (name, job_title, salary) values ('Raven', 'Developer I', 38713);
insert into EMPLOYEE (name, job_title, salary) values ('Dinnie', 'Professor', 410661);
insert into EMPLOYEE (name, job_title, salary) values ('Willi', 'Assistant Media Planner', 318303);
insert into EMPLOYEE (name, job_title, salary) values ('Delly', 'Speech Pathologist', 494423);
insert into EMPLOYEE (name, job_title, salary) values ('Eran', 'Budget/Accounting Analyst I', 273369);
insert into EMPLOYEE (name, job_title, salary) values ('Christean', 'Accountant III', 261451);
insert into EMPLOYEE (name, job_title, salary) values ('Fayth', 'Assistant Professor', 175102);
insert into EMPLOYEE (name, job_title, salary) values ('Carmon', 'Research Nurse', 204550);
insert into EMPLOYEE (name, job_title, salary) values ('Adrea', 'Analyst Programmer', 57840);
insert into EMPLOYEE (name, job_title, salary) values ('Xylina', 'Payment Adjustment Coordinator', 126173);
insert into EMPLOYEE (name, job_title, salary) values ('Angelique', 'Analog Circuit Design manager', 491212);
insert into EMPLOYEE (name, job_title, salary) values ('Renelle', 'Safety Technician II', 21938);
insert into EMPLOYEE (name, job_title, salary) values ('Leela', 'Nurse Practicioner', 137515);
insert into EMPLOYEE (name, job_title, salary) values ('Esmeralda', 'Operator', 289938);
insert into EMPLOYEE (name, job_title, salary) values ('Morganica', 'Software Consultant', 362520);
insert into EMPLOYEE (name, job_title, salary) values ('Gustie', 'Project Manager', 33004);
insert into EMPLOYEE (name, job_title, salary) values ('Brietta', 'Web Developer IV', 460780);
insert into EMPLOYEE (name, job_title, salary) values ('Nita', 'Dental Hygienist', 416102);
insert into EMPLOYEE (name, job_title, salary) values ('Rana', 'Physical Therapy Assistant', 140676);
insert into EMPLOYEE (name, job_title, salary) values ('Rosy', 'VP Accounting', 496399);
insert into EMPLOYEE (name, job_title, salary) values ('Martguerita', 'Paralegal', 213585);
insert into EMPLOYEE (name, job_title, salary) values ('Carine', 'Accountant I', 268271);
insert into EMPLOYEE (name, job_title, salary) values ('Corabella', 'Research Assistant I', 396355);
insert into EMPLOYEE (name, job_title, salary) values ('Lauraine', 'Quality Control Specialist', 10500);
insert into EMPLOYEE (name, job_title, salary) values ('Virginia', 'Structural Engineer', 238127);
insert into EMPLOYEE (name, job_title, salary) values ('Greta', 'Recruiter', 177284);
insert into EMPLOYEE (name, job_title, salary) values ('Letty', 'Compensation Analyst', 374844);
insert into EMPLOYEE (name, job_title, salary) values ('Cary', 'Food Chemist', 126577);
insert into EMPLOYEE (name, job_title, salary) values ('Nissie', 'Financial Analyst', 371660);
insert into EMPLOYEE (name, job_title, salary) values ('Robbi', 'Account Coordinator', 450163);
insert into EMPLOYEE (name, job_title, salary) values ('Maddy', 'Staff Accountant IV', 37540);
insert into EMPLOYEE (name, job_title, salary) values ('Freddi', 'Chief Design Engineer', 431634);
insert into EMPLOYEE (name, job_title, salary) values ('Bibbie', 'VP Marketing', 79329);
insert into EMPLOYEE (name, job_title, salary) values ('Dorolice', 'Tax Accountant', 57954);
insert into EMPLOYEE (name, job_title, salary) values ('Gianna', 'Technical Writer', 316916);
insert into EMPLOYEE (name, job_title, salary) values ('Lorne', 'General Manager', 428172);
insert into EMPLOYEE (name, job_title, salary) values ('Genevra', 'Paralegal', 425917);
insert into EMPLOYEE (name, job_title, salary) values ('Lyn', 'Media Manager IV', 128543);
insert into EMPLOYEE (name, job_title, salary) values ('Tressa', 'Assistant Media Planner', 232804);
insert into EMPLOYEE (name, job_title, salary) values ('Michaela', 'Editor', 442625);
insert into EMPLOYEE (name, job_title, salary) values ('Florette', 'Registered Nurse', 253359);
insert into EMPLOYEE (name, job_title, salary) values ('Johanna', 'Senior Developer', 210278);
insert into EMPLOYEE (name, job_title, salary) values ('Carmina', 'Sales Associate', 491278);
insert into EMPLOYEE (name, job_title, salary) values ('Sallee', 'Environmental Specialist', 469463);
insert into EMPLOYEE (name, job_title, salary) values ('Gunilla', 'Director of Sales', 138324);
insert into EMPLOYEE (name, job_title, salary) values ('Traci', 'Teacher', 117984);
insert into EMPLOYEE (name, job_title, salary) values ('Allx', 'Analyst Programmer', 436282);
insert into EMPLOYEE (name, job_title, salary) values ('Mil', 'Analyst Programmer', 456757);
insert into EMPLOYEE (name, job_title, salary) values ('Michaelina', 'Research Associate', 412381);
insert into EMPLOYEE (name, job_title, salary) values ('Aura', 'Nuclear Power Engineer', 109537);
insert into EMPLOYEE (name, job_title, salary) values ('Koren', 'Health Coach III', 180163);
insert into EMPLOYEE (name, job_title, salary) values ('Lavena', 'Senior Sales Associate', 454780);
insert into EMPLOYEE (name, job_title, salary) values ('Kayla', 'VP Accounting', 177013);
insert into EMPLOYEE (name, job_title, salary) values ('Christan', 'Senior Editor', 305729);
insert into EMPLOYEE (name, job_title, salary) values ('Fredi', 'Web Developer IV', 490045);
insert into EMPLOYEE (name, job_title, salary) values ('Carlene', 'Assistant Media Planner', 218046);
insert into EMPLOYEE (name, job_title, salary) values ('Katina', 'Office Assistant II', 487009);
insert into EMPLOYEE (name, job_title, salary) values ('Leodora', 'Electrical Engineer', 296674);
insert into EMPLOYEE (name, job_title, salary) values ('Melanie', 'Executive Secretary', 22006);
insert into EMPLOYEE (name, job_title, salary) values ('Olivia', 'VP Marketing', 366096);
insert into EMPLOYEE (name, job_title, salary) values ('Guinevere', 'Administrative Assistant II', 234752);
insert into EMPLOYEE (name, job_title, salary) values ('Cathleen', 'GIS Technical Architect', 413915);
insert into EMPLOYEE (name, job_title, salary) values ('Leonie', 'Staff Scientist', 418419);
insert into EMPLOYEE (name, job_title, salary) values ('Zorah', 'VP Product Management', 123790);
insert into EMPLOYEE (name, job_title, salary) values ('Rori', 'Developer I', 168499);
insert into EMPLOYEE (name, job_title, salary) values ('Benedetta', 'Legal Assistant', 373218);
insert into EMPLOYEE (name, job_title, salary) values ('Bonnibelle', 'Civil Engineer', 167229);
insert into EMPLOYEE (name, job_title, salary) values ('Eunice', 'Human Resources Manager', 76469);
insert into EMPLOYEE (name, job_title, salary) values ('Fianna', 'Biostatistician II', 288309);
insert into EMPLOYEE (name, job_title, salary) values ('Opaline', 'Civil Engineer', 100439);
insert into EMPLOYEE (name, job_title, salary) values ('Dolly', 'Payment Adjustment Coordinator', 255247);
insert into EMPLOYEE (name, job_title, salary) values ('Melisande', 'Software Test Engineer I', 311789);
insert into EMPLOYEE (name, job_title, salary) values ('Fianna', 'Environmental Specialist', 55131);
insert into EMPLOYEE (name, job_title, salary) values ('Sibeal', 'Developer I', 214470);
insert into EMPLOYEE (name, job_title, salary) values ('Mirilla', 'GIS Technical Architect', 234426);
insert into EMPLOYEE (name, job_title, salary) values ('Gretta', 'Software Engineer III', 353317);
insert into EMPLOYEE (name, job_title, salary) values ('Eunice', 'Design Engineer', 24715);
insert into EMPLOYEE (name, job_title, salary) values ('Raphaela', 'Civil Engineer', 287688);
insert into EMPLOYEE (name, job_title, salary) values ('Fey', 'Compensation Analyst', 499903);
insert into EMPLOYEE (name, job_title, salary) values ('Page', 'Editor', 348513);
insert into EMPLOYEE (name, job_title, salary) values ('Johna', 'GIS Technical Architect', 408713);
insert into EMPLOYEE (name, job_title, salary) values ('Aprilette', 'Marketing Assistant', 96332);
insert into EMPLOYEE (name, job_title, salary) values ('Ange', 'Web Designer II', 49118);
insert into EMPLOYEE (name, job_title, salary) values ('Andi', 'Help Desk Technician', 93203);
insert into EMPLOYEE (name, job_title, salary) values ('Selene', 'Help Desk Technician', 407543);
insert into EMPLOYEE (name, job_title, salary) values ('Janet', 'Business Systems Development Analyst', 314630);
insert into EMPLOYEE (name, job_title, salary) values ('Gerrie', 'Administrative Assistant I', 298651);
insert into EMPLOYEE (name, job_title, salary) values ('Tabbie', 'Quality Engineer', 79781);
insert into EMPLOYEE (name, job_title, salary) values ('Cherie', 'Professor', 400599);
insert into EMPLOYEE (name, job_title, salary) values ('Ludovika', 'Human Resources Assistant III', 54478);
insert into EMPLOYEE (name, job_title, salary) values ('Abigale', 'Physical Therapy Assistant', 241206);
insert into EMPLOYEE (name, job_title, salary) values ('Mariya', 'Accountant III', 55845);
insert into EMPLOYEE (name, job_title, salary) values ('Estell', 'Software Engineer I', 175055);
insert into EMPLOYEE (name, job_title, salary) values ('Lorene', 'Account Representative I', 359040);
insert into EMPLOYEE (name, job_title, salary) values ('Shawnee', 'Mechanical Systems Engineer', 125256);
insert into EMPLOYEE (name, job_title, salary) values ('Stacy', 'Staff Accountant IV', 387982);
insert into EMPLOYEE (name, job_title, salary) values ('Roshelle', 'Biostatistician I', 189785);
insert into EMPLOYEE (name, job_title, salary) values ('Tybie', 'Geological Engineer', 391444);
insert into EMPLOYEE (name, job_title, salary) values ('Feodora', 'GIS Technical Architect', 55104);
insert into EMPLOYEE (name, job_title, salary) values ('Pollyanna', 'Human Resources Manager', 331566);
insert into EMPLOYEE (name, job_title, salary) values ('Judie', 'Financial Advisor', 130640);
insert into EMPLOYEE (name, job_title, salary) values ('Orel', 'Software Consultant', 495895);
insert into EMPLOYEE (name, job_title, salary) values ('Carolan', 'Senior Financial Analyst', 455837);
insert into EMPLOYEE (name, job_title, salary) values ('Lynna', 'Quality Engineer', 198722);
insert into EMPLOYEE (name, job_title, salary) values ('Stefania', 'Librarian', 348900);
insert into EMPLOYEE (name, job_title, salary) values ('Anabelle', 'VP Quality Control', 281811);
insert into EMPLOYEE (name, job_title, salary) values ('Penelope', 'Junior Executive', 140165);
insert into EMPLOYEE (name, job_title, salary) values ('Madalyn', 'VP Marketing', 434951);
insert into EMPLOYEE (name, job_title, salary) values ('Kaila', 'Accounting Assistant IV', 467113);
insert into EMPLOYEE (name, job_title, salary) values ('Ofella', 'Graphic Designer', 227101);
insert into EMPLOYEE (name, job_title, salary) values ('Salli', 'Information Systems Manager', 211393);
insert into EMPLOYEE (name, job_title, salary) values ('Hannis', 'Geologist IV', 470388);
insert into EMPLOYEE (name, job_title, salary) values ('Sada', 'Technical Writer', 273528);
insert into EMPLOYEE (name, job_title, salary) values ('Kira', 'Account Executive', 428716);
insert into EMPLOYEE (name, job_title, salary) values ('Linnet', 'Biostatistician II', 155656);
insert into EMPLOYEE (name, job_title, salary) values ('Auguste', 'Programmer Analyst III', 188822);
insert into EMPLOYEE (name, job_title, salary) values ('Fiorenze', 'Chemical Engineer', 28751);
insert into EMPLOYEE (name, job_title, salary) values ('Maureen', 'Budget/Accounting Analyst III', 227279);
insert into EMPLOYEE (name, job_title, salary) values ('Renata', 'Librarian', 417019);
insert into EMPLOYEE (name, job_title, salary) values ('Edin', 'Help Desk Operator', 170005);
insert into EMPLOYEE (name, job_title, salary) values ('Shanon', 'Research Associate', 381109);
insert into EMPLOYEE (name, job_title, salary) values ('Beret', 'Legal Assistant', 88035);
insert into EMPLOYEE (name, job_title, salary) values ('Deerdre', 'Analog Circuit Design manager', 272499);
insert into EMPLOYEE (name, job_title, salary) values ('Roslyn', 'Senior Developer', 230256);
insert into EMPLOYEE (name, job_title, salary) values ('Luce', 'Recruiting Manager', 180213);
insert into EMPLOYEE (name, job_title, salary) values ('Grayce', 'VP Marketing', 309540);
insert into EMPLOYEE (name, job_title, salary) values ('Zorah', 'Dental Hygienist', 261091);
insert into EMPLOYEE (name, job_title, salary) values ('Renee', 'Programmer Analyst II', 90313);
insert into EMPLOYEE (name, job_title, salary) values ('Lee', 'Occupational Therapist', 60659);
insert into EMPLOYEE (name, job_title, salary) values ('Kellyann', 'Engineer I', 40086);
insert into EMPLOYEE (name, job_title, salary) values ('Gabbie', 'Registered Nurse', 23653);
insert into EMPLOYEE (name, job_title, salary) values ('Kassie', 'Design Engineer', 81684);
insert into EMPLOYEE (name, job_title, salary) values ('Conni', 'Structural Engineer', 102262);
insert into EMPLOYEE (name, job_title, salary) values ('Corrina', 'Sales Associate', 67368);
insert into EMPLOYEE (name, job_title, salary) values ('Blisse', 'VP Product Management', 335571);
insert into EMPLOYEE (name, job_title, salary) values ('Karilynn', 'Research Assistant I', 17914);
insert into EMPLOYEE (name, job_title, salary) values ('Jannelle', 'Structural Analysis Engineer', 211282);
insert into EMPLOYEE (name, job_title, salary) values ('Timmie', 'Human Resources Manager', 307032);
insert into EMPLOYEE (name, job_title, salary) values ('Andree', 'Business Systems Development Analyst', 465839);
insert into EMPLOYEE (name, job_title, salary) values ('Estele', 'Food Chemist', 119584);
insert into EMPLOYEE (name, job_title, salary) values ('Kyle', 'Accounting Assistant III', 344580);
insert into EMPLOYEE (name, job_title, salary) values ('Roxine', 'Senior Cost Accountant', 486512);
insert into EMPLOYEE (name, job_title, salary) values ('Arluene', 'Product Engineer', 474943);
insert into EMPLOYEE (name, job_title, salary) values ('Jemmy', 'Clinical Specialist', 267691);
insert into EMPLOYEE (name, job_title, salary) values ('Miranda', 'Nurse', 432716);
insert into EMPLOYEE (name, job_title, salary) values ('Adaline', 'Quality Engineer', 368778);
insert into EMPLOYEE (name, job_title, salary) values ('Carita', 'Biostatistician IV', 425054);
insert into EMPLOYEE (name, job_title, salary) values ('Janina', 'Information Systems Manager', 132474);
insert into EMPLOYEE (name, job_title, salary) values ('Clarette', 'Paralegal', 98321);
insert into EMPLOYEE (name, job_title, salary) values ('Lynnell', 'Environmental Specialist', 289263);
insert into EMPLOYEE (name, job_title, salary) values ('Minni', 'Dental Hygienist', 364753);
insert into EMPLOYEE (name, job_title, salary) values ('Marena', 'Account Executive', 302558);
insert into EMPLOYEE (name, job_title, salary) values ('Minetta', 'Accounting Assistant I', 289505);
insert into EMPLOYEE (name, job_title, salary) values ('Elfrieda', 'Teacher', 219302);
insert into EMPLOYEE (name, job_title, salary) values ('Rubia', 'VP Quality Control', 317615);
insert into EMPLOYEE (name, job_title, salary) values ('Roselin', 'VP Accounting', 285795);
insert into EMPLOYEE (name, job_title, salary) values ('Henka', 'Web Designer II', 47687);
insert into EMPLOYEE (name, job_title, salary) values ('Stephani', 'Design Engineer', 442169);
insert into EMPLOYEE (name, job_title, salary) values ('Zorine', 'Environmental Tech', 158045);
insert into EMPLOYEE (name, job_title, salary) values ('Kaitlin', 'Administrative Assistant IV', 51926);
insert into EMPLOYEE (name, job_title, salary) values ('Alexa', 'Physical Therapy Assistant', 187794);
insert into EMPLOYEE (name, job_title, salary) values ('Ora', 'Staff Scientist', 359728);
insert into EMPLOYEE (name, job_title, salary) values ('Marya', 'Programmer III', 401050);
insert into EMPLOYEE (name, job_title, salary) values ('Lacy', 'Desktop Support Technician', 436597);
insert into EMPLOYEE (name, job_title, salary) values ('Loutitia', 'Senior Financial Analyst', 50308);
insert into EMPLOYEE (name, job_title, salary) values ('Theresita', 'Software Test Engineer I', 209730);
insert into EMPLOYEE (name, job_title, salary) values ('Loni', 'Office Assistant I', 291900);
insert into EMPLOYEE (name, job_title, salary) values ('Kath', 'Computer Systems Analyst IV', 221485);
insert into EMPLOYEE (name, job_title, salary) values ('Eliza', 'Marketing Assistant', 438707);
insert into EMPLOYEE (name, job_title, salary) values ('Petronille', 'Food Chemist', 80845);
insert into EMPLOYEE (name, job_title, salary) values ('Danna', 'Engineer III', 283280);
insert into EMPLOYEE (name, job_title, salary) values ('Doti', 'Community Outreach Specialist', 10458);
insert into EMPLOYEE (name, job_title, salary) values ('Alix', 'Design Engineer', 439222);
insert into EMPLOYEE (name, job_title, salary) values ('Kaycee', 'Senior Quality Engineer', 73463);
insert into EMPLOYEE (name, job_title, salary) values ('Jocelin', 'Chemical Engineer', 130599);
insert into EMPLOYEE (name, job_title, salary) values ('Halie', 'Design Engineer', 274477);
insert into EMPLOYEE (name, job_title, salary) values ('Happy', 'Desktop Support Technician', 61560);
insert into EMPLOYEE (name, job_title, salary) values ('Tierney', 'Nurse', 81437);
insert into EMPLOYEE (name, job_title, salary) values ('Josie', 'GIS Technical Architect', 406763);
insert into EMPLOYEE (name, job_title, salary) values ('Lyndel', 'Software Engineer III', 372728);
insert into EMPLOYEE (name, job_title, salary) values ('Jacintha', 'Research Nurse', 134059);
insert into EMPLOYEE (name, job_title, salary) values ('Amalea', 'Food Chemist', 319595);
insert into EMPLOYEE (name, job_title, salary) values ('Cher', 'Analyst Programmer', 62567);
insert into EMPLOYEE (name, job_title, salary) values ('Arly', 'Nurse Practicioner', 199514);
insert into EMPLOYEE (name, job_title, salary) values ('Delora', 'Executive Secretary', 483180);
insert into EMPLOYEE (name, job_title, salary) values ('Kath', 'Data Coordiator', 246934);
insert into EMPLOYEE (name, job_title, salary) values ('Ulrikaumeko', 'Technical Writer', 98312);
insert into EMPLOYEE (name, job_title, salary) values ('Glori', 'Paralegal', 111717);
insert into EMPLOYEE (name, job_title, salary) values ('Brynn', 'Software Consultant', 103424);
insert into EMPLOYEE (name, job_title, salary) values ('Brittni', 'Paralegal', 239122);
insert into EMPLOYEE (name, job_title, salary) values ('Elna', 'Safety Technician II', 441819);
insert into EMPLOYEE (name, job_title, salary) values ('Joella', 'VP Marketing', 199711);
insert into EMPLOYEE (name, job_title, salary) values ('Happy', 'Editor', 296784);
insert into EMPLOYEE (name, job_title, salary) values ('Corabelle', 'Sales Associate', 102718);
insert into EMPLOYEE (name, job_title, salary) values ('Esther', 'Operator', 35730);
insert into EMPLOYEE (name, job_title, salary) values ('Marlie', 'Occupational Therapist', 303224);
insert into EMPLOYEE (name, job_title, salary) values ('Jenica', 'Sales Associate', 385812);
insert into EMPLOYEE (name, job_title, salary) values ('Noel', 'Compensation Analyst', 311594);
insert into EMPLOYEE (name, job_title, salary) values ('Lani', 'Internal Auditor', 132823);
insert into EMPLOYEE (name, job_title, salary) values ('Maiga', 'Dental Hygienist', 447162);
insert into EMPLOYEE (name, job_title, salary) values ('Emilie', 'Statistician I', 181902);
insert into EMPLOYEE (name, job_title, salary) values ('Dorotea', 'Recruiting Manager', 477080);
insert into EMPLOYEE (name, job_title, salary) values ('Emili', 'Social Worker', 499816);
insert into EMPLOYEE (name, job_title, salary) values ('Nikaniki', 'Mechanical Systems Engineer', 317417);
insert into EMPLOYEE (name, job_title, salary) values ('Kristen', 'Physical Therapy Assistant', 30622);
insert into EMPLOYEE (name, job_title, salary) values ('Torie', 'Programmer Analyst IV', 456340);
insert into EMPLOYEE (name, job_title, salary) values ('Karlene', 'Social Worker', 181859);
insert into EMPLOYEE (name, job_title, salary) values ('Delila', 'Associate Professor', 298420);
insert into EMPLOYEE (name, job_title, salary) values ('Missie', 'VP Marketing', 404571);
insert into EMPLOYEE (name, job_title, salary) values ('Anestassia', 'Nurse', 271407);
insert into EMPLOYEE (name, job_title, salary) values ('Michaella', 'Administrative Officer', 446262);
insert into EMPLOYEE (name, job_title, salary) values ('Kata', 'Pharmacist', 464043);
insert into EMPLOYEE (name, job_title, salary) values ('Devinne', 'Tax Accountant', 177003);
insert into EMPLOYEE (name, job_title, salary) values ('Billye', 'Director of Sales', 468638);
insert into EMPLOYEE (name, job_title, salary) values ('Lucie', 'Software Consultant', 480345);
insert into EMPLOYEE (name, job_title, salary) values ('Doti', 'Community Outreach Specialist', 49906);
insert into EMPLOYEE (name, job_title, salary) values ('Clio', 'Assistant Manager', 476199);
insert into EMPLOYEE (name, job_title, salary) values ('Stacie', 'Technical Writer', 335089);
insert into EMPLOYEE (name, job_title, salary) values ('Edithe', 'Paralegal', 469845);
insert into EMPLOYEE (name, job_title, salary) values ('Addia', 'Analog Circuit Design manager', 286110);
insert into EMPLOYEE (name, job_title, salary) values ('Gilbertine', 'Assistant Manager', 210327);
insert into EMPLOYEE (name, job_title, salary) values ('Elayne', 'Actuary', 402746);
insert into EMPLOYEE (name, job_title, salary) values ('Karoly', 'Research Associate', 474411);
insert into EMPLOYEE (name, job_title, salary) values ('Jody', 'Help Desk Technician', 158736);
insert into EMPLOYEE (name, job_title, salary) values ('Lorine', 'VP Quality Control', 344035);
insert into EMPLOYEE (name, job_title, salary) values ('Anatola', 'Health Coach I', 226078);
insert into EMPLOYEE (name, job_title, salary) values ('Sydel', 'Desktop Support Technician', 363629);
insert into EMPLOYEE (name, job_title, salary) values ('Kasey', 'Pharmacist', 471852);
insert into EMPLOYEE (name, job_title, salary) values ('Natka', 'Programmer Analyst I', 401390);
insert into EMPLOYEE (name, job_title, salary) values ('Ladonna', 'Media Manager III', 143834);
insert into EMPLOYEE (name, job_title, salary) values ('Lenore', 'Developer I', 318184);
insert into EMPLOYEE (name, job_title, salary) values ('Grata', 'Systems Administrator I', 452545);
insert into EMPLOYEE (name, job_title, salary) values ('Chiquita', 'Web Designer I', 15404);
insert into EMPLOYEE (name, job_title, salary) values ('Anne-marie', 'Software Consultant', 289542);
insert into EMPLOYEE (name, job_title, salary) values ('Rhianon', 'Office Assistant IV', 103590);
insert into EMPLOYEE (name, job_title, salary) values ('Iona', 'Safety Technician I', 145389);
insert into EMPLOYEE (name, job_title, salary) values ('Peria', 'Programmer III', 478393);
insert into EMPLOYEE (name, job_title, salary) values ('Maurine', 'Environmental Tech', 369384);
insert into EMPLOYEE (name, job_title, salary) values ('Anna-maria', 'Junior Executive', 423858);
insert into EMPLOYEE (name, job_title, salary) values ('Alecia', 'Systems Administrator I', 10530);
insert into EMPLOYEE (name, job_title, salary) values ('Nettie', 'Senior Developer', 268474);
insert into EMPLOYEE (name, job_title, salary) values ('Meridel', 'Nurse', 177866);
insert into EMPLOYEE (name, job_title, salary) values ('Andriana', 'Research Nurse', 453936);
insert into EMPLOYEE (name, job_title, salary) values ('Valaria', 'Engineer II', 308609);
insert into EMPLOYEE (name, job_title, salary) values ('Loella', 'Web Developer I', 499939);
insert into EMPLOYEE (name, job_title, salary) values ('Missy', 'Developer I', 199426);
insert into EMPLOYEE (name, job_title, salary) values ('Pia', 'Media Manager IV', 295366);
insert into EMPLOYEE (name, job_title, salary) values ('Kimmy', 'Analog Circuit Design manager', 359289);
insert into EMPLOYEE (name, job_title, salary) values ('Heddie', 'Recruiting Manager', 226787);
insert into EMPLOYEE (name, job_title, salary) values ('Kameko', 'Information Systems Manager', 396069);
insert into EMPLOYEE (name, job_title, salary) values ('Dulcine', 'VP Marketing', 148330);
insert into EMPLOYEE (name, job_title, salary) values ('Tatiania', 'Speech Pathologist', 150658);
insert into EMPLOYEE (name, job_title, salary) values ('Leia', 'Software Consultant', 228518);
insert into EMPLOYEE (name, job_title, salary) values ('Malvina', 'Senior Editor', 337620);
insert into EMPLOYEE (name, job_title, salary) values ('Gelya', 'Analog Circuit Design manager', 57378);
insert into EMPLOYEE (name, job_title, salary) values ('Winonah', 'VP Quality Control', 461169);
insert into EMPLOYEE (name, job_title, salary) values ('Yettie', 'Human Resources Manager', 166015);
insert into EMPLOYEE (name, job_title, salary) values ('Chiarra', 'Speech Pathologist', 378908);
insert into EMPLOYEE (name, job_title, salary) values ('Cristin', 'Junior Executive', 359264);
insert into EMPLOYEE (name, job_title, salary) values ('Kristien', 'Senior Developer', 390082);
insert into EMPLOYEE (name, job_title, salary) values ('Allyn', 'Research Nurse', 431488);
insert into EMPLOYEE (name, job_title, salary) values ('Ardith', 'VP Product Management', 360152);
insert into EMPLOYEE (name, job_title, salary) values ('Tabby', 'Recruiting Manager', 302690);
insert into EMPLOYEE (name, job_title, salary) values ('Sybille', 'Research Associate', 167732);
insert into EMPLOYEE (name, job_title, salary) values ('Florencia', 'Administrative Officer', 114258);
insert into EMPLOYEE (name, job_title, salary) values ('Collete', 'Nurse', 226078);
insert into EMPLOYEE (name, job_title, salary) values ('Brunhilde', 'Speech Pathologist', 134332);
insert into EMPLOYEE (name, job_title, salary) values ('Meara', 'Marketing Manager', 70807);
insert into EMPLOYEE (name, job_title, salary) values ('Freddie', 'Sales Associate', 426541);
insert into EMPLOYEE (name, job_title, salary) values ('Karen', 'Junior Executive', 162236);
insert into EMPLOYEE (name, job_title, salary) values ('Edithe', 'Tax Accountant', 69626);
insert into EMPLOYEE (name, job_title, salary) values ('Nerissa', 'Mechanical Systems Engineer', 105689);
insert into EMPLOYEE (name, job_title, salary) values ('Atlanta', 'Chief Design Engineer', 241609);
insert into EMPLOYEE (name, job_title, salary) values ('Rozella', 'Data Coordiator', 91666);
insert into EMPLOYEE (name, job_title, salary) values ('Dorris', 'Desktop Support Technician', 184096);
insert into EMPLOYEE (name, job_title, salary) values ('Nannie', 'Analyst Programmer', 181264);
insert into EMPLOYEE (name, job_title, salary) values ('Darci', 'VP Quality Control', 422802);
insert into EMPLOYEE (name, job_title, salary) values ('Crystal', 'Technical Writer', 279126);
insert into EMPLOYEE (name, job_title, salary) values ('Teddy', 'Structural Engineer', 23656);
insert into EMPLOYEE (name, job_title, salary) values ('Wren', 'Speech Pathologist', 81269);
insert into EMPLOYEE (name, job_title, salary) values ('Marlene', 'Environmental Specialist', 404355);
insert into EMPLOYEE (name, job_title, salary) values ('Kris', 'VP Marketing', 301700);
insert into EMPLOYEE (name, job_title, salary) values ('Hedwig', 'Product Engineer', 265368);
insert into EMPLOYEE (name, job_title, salary) values ('Inga', 'Geologist III', 271863);
insert into EMPLOYEE (name, job_title, salary) values ('Farah', 'Assistant Media Planner', 341354);
insert into EMPLOYEE (name, job_title, salary) values ('Nan', 'VP Marketing', 153027);
insert into EMPLOYEE (name, job_title, salary) values ('Deedee', 'Environmental Tech', 326683);
insert into EMPLOYEE (name, job_title, salary) values ('Jannel', 'Quality Engineer', 318129);
insert into EMPLOYEE (name, job_title, salary) values ('Lorita', 'Payment Adjustment Coordinator', 445168);
insert into EMPLOYEE (name, job_title, salary) values ('Fanchette', 'Product Engineer', 321250);
insert into EMPLOYEE (name, job_title, salary) values ('Monika', 'Community Outreach Specialist', 130306);
insert into EMPLOYEE (name, job_title, salary) values ('Daron', 'Software Test Engineer IV', 266447);
insert into EMPLOYEE (name, job_title, salary) values ('Tamera', 'Operator', 259823);
insert into EMPLOYEE (name, job_title, salary) values ('Theresita', 'Structural Engineer', 216754);
insert into EMPLOYEE (name, job_title, salary) values ('Adrianna', 'Associate Professor', 54881);
insert into EMPLOYEE (name, job_title, salary) values ('Timmi', 'Nurse Practicioner', 418351);
insert into EMPLOYEE (name, job_title, salary) values ('Fleurette', 'Chemical Engineer', 43918);
insert into EMPLOYEE (name, job_title, salary) values ('Orella', 'Social Worker', 275753);
insert into EMPLOYEE (name, job_title, salary) values ('Carine', 'Internal Auditor', 255533);
insert into EMPLOYEE (name, job_title, salary) values ('Evangeline', 'Recruiter', 213147);
insert into EMPLOYEE (name, job_title, salary) values ('Erinna', 'Technical Writer', 372166);
insert into EMPLOYEE (name, job_title, salary) values ('Aarika', 'Payment Adjustment Coordinator', 265667);
insert into EMPLOYEE (name, job_title, salary) values ('Viva', 'Research Assistant III', 150112);
insert into EMPLOYEE (name, job_title, salary) values ('Carmelle', 'Geological Engineer', 68471);
insert into EMPLOYEE (name, job_title, salary) values ('Courtnay', 'Senior Sales Associate', 264250);
insert into EMPLOYEE (name, job_title, salary) values ('Danette', 'Internal Auditor', 135009);
insert into EMPLOYEE (name, job_title, salary) values ('Morna', 'Project Manager', 454731);
insert into EMPLOYEE (name, job_title, salary) values ('Jennie', 'Help Desk Technician', 260607);
insert into EMPLOYEE (name, job_title, salary) values ('Rozele', 'Senior Editor', 330284);
insert into EMPLOYEE (name, job_title, salary) values ('Leia', 'Quality Control Specialist', 316883);
insert into EMPLOYEE (name, job_title, salary) values ('Felicle', 'Help Desk Operator', 282135);
insert into EMPLOYEE (name, job_title, salary) values ('Katherina', 'Senior Financial Analyst', 306202);
insert into EMPLOYEE (name, job_title, salary) values ('Meris', 'Senior Quality Engineer', 410066);
insert into EMPLOYEE (name, job_title, salary) values ('Norry', 'Recruiter', 246230);
insert into EMPLOYEE (name, job_title, salary) values ('Fawne', 'Structural Engineer', 461668);
insert into EMPLOYEE (name, job_title, salary) values ('Anthea', 'Marketing Manager', 296086);
insert into EMPLOYEE (name, job_title, salary) values ('Ceciley', 'Design Engineer', 28713);
insert into EMPLOYEE (name, job_title, salary) values ('Antonie', 'Developer III', 489320);
insert into EMPLOYEE (name, job_title, salary) values ('Esmaria', 'Nurse', 305624);
insert into EMPLOYEE (name, job_title, salary) values ('Carlotta', 'Administrative Officer', 347002);
insert into EMPLOYEE (name, job_title, salary) values ('Michel', 'Compensation Analyst', 253553);
insert into EMPLOYEE (name, job_title, salary) values ('Merola', 'Human Resources Manager', 303640);
insert into EMPLOYEE (name, job_title, salary) values ('Carroll', 'Accountant I', 294226);
insert into EMPLOYEE (name, job_title, salary) values ('Dyann', 'GIS Technical Architect', 253904);
insert into EMPLOYEE (name, job_title, salary) values ('Genny', 'Automation Specialist II', 167020);
insert into EMPLOYEE (name, job_title, salary) values ('Mildred', 'Electrical Engineer', 208438);
insert into EMPLOYEE (name, job_title, salary) values ('Kissee', 'Budget/Accounting Analyst IV', 59885);
insert into EMPLOYEE (name, job_title, salary) values ('Chrysler', 'Administrative Officer', 128273);
insert into EMPLOYEE (name, job_title, salary) values ('Nancey', 'Assistant Professor', 67036);
insert into EMPLOYEE (name, job_title, salary) values ('Irene', 'Senior Editor', 208723);
insert into EMPLOYEE (name, job_title, salary) values ('Katee', 'Staff Scientist', 78410);
insert into EMPLOYEE (name, job_title, salary) values ('Phylys', 'Assistant Manager', 119158);
insert into EMPLOYEE (name, job_title, salary) values ('Crista', 'Staff Scientist', 280509);
insert into EMPLOYEE (name, job_title, salary) values ('Cara', 'Computer Systems Analyst II', 287721);
insert into EMPLOYEE (name, job_title, salary) values ('Orsola', 'Analyst Programmer', 341135);
insert into EMPLOYEE (name, job_title, salary) values ('Cherry', 'Computer Systems Analyst IV', 455958);
insert into EMPLOYEE (name, job_title, salary) values ('Kania', 'Database Administrator I', 466752);
insert into EMPLOYEE (name, job_title, salary) values ('Torie', 'Electrical Engineer', 428945);
insert into EMPLOYEE (name, job_title, salary) values ('Valida', 'Director of Sales', 461264);
insert into EMPLOYEE (name, job_title, salary) values ('Sarajane', 'Registered Nurse', 216837);
insert into EMPLOYEE (name, job_title, salary) values ('Noell', 'Design Engineer', 227181);
insert into EMPLOYEE (name, job_title, salary) values ('Alfy', 'Assistant Manager', 219443);
insert into EMPLOYEE (name, job_title, salary) values ('Milissent', 'Human Resources Manager', 300037);
insert into EMPLOYEE (name, job_title, salary) values ('Janis', 'Financial Advisor', 109265);
insert into EMPLOYEE (name, job_title, salary) values ('Dorri', 'Staff Accountant I', 173563);
insert into EMPLOYEE (name, job_title, salary) values ('Fran', 'Physical Therapy Assistant', 270741);
insert into EMPLOYEE (name, job_title, salary) values ('Ramona', 'Administrative Assistant IV', 457976);
insert into EMPLOYEE (name, job_title, salary) values ('Livia', 'Assistant Media Planner', 326243);
insert into EMPLOYEE (name, job_title, salary) values ('Rosie', 'Staff Scientist', 36833);
insert into EMPLOYEE (name, job_title, salary) values ('Mozelle', 'Occupational Therapist', 448963);
insert into EMPLOYEE (name, job_title, salary) values ('Faydra', 'Budget/Accounting Analyst III', 32933);
insert into EMPLOYEE (name, job_title, salary) values ('Doloritas', 'Systems Administrator I', 401074);
insert into EMPLOYEE (name, job_title, salary) values ('Wilona', 'Staff Scientist', 493084);
insert into EMPLOYEE (name, job_title, salary) values ('Clotilda', 'VP Sales', 210602);
insert into EMPLOYEE (name, job_title, salary) values ('Lorita', 'Staff Scientist', 327565);
insert into EMPLOYEE (name, job_title, salary) values ('Nelle', 'Administrative Officer', 281411);
insert into EMPLOYEE (name, job_title, salary) values ('Aurel', 'Electrical Engineer', 352467);
insert into EMPLOYEE (name, job_title, salary) values ('Margarete', 'Research Nurse', 203419);
insert into EMPLOYEE (name, job_title, salary) values ('Dixie', 'Accounting Assistant IV', 486917);
insert into EMPLOYEE (name, job_title, salary) values ('Atlante', 'VP Accounting', 281597);
insert into EMPLOYEE (name, job_title, salary) values ('Ricca', 'Environmental Tech', 414056);
insert into EMPLOYEE (name, job_title, salary) values ('Michaela', 'Librarian', 453421);
insert into EMPLOYEE (name, job_title, salary) values ('Inger', 'VP Sales', 490999);
insert into EMPLOYEE (name, job_title, salary) values ('Edeline', 'Help Desk Technician', 203541);
insert into EMPLOYEE (name, job_title, salary) values ('Abigale', 'Legal Assistant', 59455);
insert into EMPLOYEE (name, job_title, salary) values ('Caril', 'Nurse', 354416);
insert into EMPLOYEE (name, job_title, salary) values ('Laurie', 'Accounting Assistant IV', 285991);
insert into EMPLOYEE (name, job_title, salary) values ('Issy', 'Operator', 242456);
insert into EMPLOYEE (name, job_title, salary) values ('Ginnifer', 'Administrative Officer', 331284);
insert into EMPLOYEE (name, job_title, salary) values ('Cristie', 'Software Consultant', 239459);
insert into EMPLOYEE (name, job_title, salary) values ('Malia', 'Account Representative IV', 229299);
insert into EMPLOYEE (name, job_title, salary) values ('Clareta', 'Design Engineer', 110000);
insert into EMPLOYEE (name, job_title, salary) values ('Rosanna', 'VP Sales', 229384);
insert into EMPLOYEE (name, job_title, salary) values ('Doralynne', 'Recruiting Manager', 361896);
insert into EMPLOYEE (name, job_title, salary) values ('Dorena', 'Business Systems Development Analyst', 289178);
insert into EMPLOYEE (name, job_title, salary) values ('Gilbertina', 'Food Chemist', 158190);
insert into EMPLOYEE (name, job_title, salary) values ('Juanita', 'Software Test Engineer III', 414459);
insert into EMPLOYEE (name, job_title, salary) values ('Rita', 'Senior Quality Engineer', 215131);
insert into EMPLOYEE (name, job_title, salary) values ('Beverlee', 'Environmental Tech', 126224);
insert into EMPLOYEE (name, job_title, salary) values ('Tally', 'Cost Accountant', 471140);
insert into EMPLOYEE (name, job_title, salary) values ('Eugine', 'VP Accounting', 71690);
insert into EMPLOYEE (name, job_title, salary) values ('Coralie', 'Speech Pathologist', 54426);
insert into EMPLOYEE (name, job_title, salary) values ('Ariela', 'Office Assistant I', 14152);
insert into EMPLOYEE (name, job_title, salary) values ('Rania', 'Professor', 40922);
insert into EMPLOYEE (name, job_title, salary) values ('Karol', 'Administrative Officer', 484528);
insert into EMPLOYEE (name, job_title, salary) values ('Tommy', 'Marketing Assistant', 78971);
insert into EMPLOYEE (name, job_title, salary) values ('Torrie', 'Mechanical Systems Engineer', 110736);
insert into EMPLOYEE (name, job_title, salary) values ('Glenna', 'Quality Engineer', 17059);
insert into EMPLOYEE (name, job_title, salary) values ('Chastity', 'Automation Specialist I', 63554);
insert into EMPLOYEE (name, job_title, salary) values ('Katinka', 'Computer Systems Analyst II', 411175);
insert into EMPLOYEE (name, job_title, salary) values ('Jerrine', 'Nuclear Power Engineer', 211898);
insert into EMPLOYEE (name, job_title, salary) values ('Maris', 'Internal Auditor', 499208);
insert into EMPLOYEE (name, job_title, salary) values ('Renelle', 'Associate Professor', 46920);
insert into EMPLOYEE (name, job_title, salary) values ('Jolie', 'Recruiting Manager', 214937);
insert into EMPLOYEE (name, job_title, salary) values ('Lesley', 'Analyst Programmer', 444428);
insert into EMPLOYEE (name, job_title, salary) values ('Hendrika', 'Assistant Media Planner', 230680);
insert into EMPLOYEE (name, job_title, salary) values ('Rosalyn', 'Research Assistant IV', 283453);
insert into EMPLOYEE (name, job_title, salary) values ('Cinda', 'Senior Sales Associate', 200545);
insert into EMPLOYEE (name, job_title, salary) values ('Felicdad', 'Assistant Professor', 173841);
insert into EMPLOYEE (name, job_title, salary) values ('Joana', 'Assistant Media Planner', 219466);
insert into EMPLOYEE (name, job_title, salary) values ('Katheryn', 'Teacher', 484398);
insert into EMPLOYEE (name, job_title, salary) values ('Rose', 'Financial Analyst', 90448);
insert into EMPLOYEE (name, job_title, salary) values ('Lizzie', 'Senior Developer', 408806);
insert into EMPLOYEE (name, job_title, salary) values ('Florrie', 'Structural Analysis Engineer', 493203);
insert into EMPLOYEE (name, job_title, salary) values ('Min', 'Statistician III', 385394);
insert into EMPLOYEE (name, job_title, salary) values ('Clarissa', 'Developer IV', 140916);
insert into EMPLOYEE (name, job_title, salary) values ('Marcile', 'Human Resources Manager', 198418);
insert into EMPLOYEE (name, job_title, salary) values ('Tracey', 'General Manager', 255019);
insert into EMPLOYEE (name, job_title, salary) values ('Gertrude', 'Pharmacist', 363563);
insert into EMPLOYEE (name, job_title, salary) values ('Edwina', 'Staff Scientist', 157687);
insert into EMPLOYEE (name, job_title, salary) values ('Nancey', 'Professor', 57683);
insert into EMPLOYEE (name, job_title, salary) values ('Madelyn', 'Developer I', 12513);
insert into EMPLOYEE (name, job_title, salary) values ('Emlynne', 'Project Manager', 176415);
insert into EMPLOYEE (name, job_title, salary) values ('Athene', 'Account Representative I', 65052);
insert into EMPLOYEE (name, job_title, salary) values ('Blondie', 'Chief Design Engineer', 446648);
insert into EMPLOYEE (name, job_title, salary) values ('Lynea', 'Registered Nurse', 247488);
